/* Searchable PDF output. Typography is embedded; content is laid out as text. */
window.BriefPDF={async export(project,palette,slug){
 const {jsPDF}=window.jspdf, pdf=new jsPDF({unit:'pt',format:'letter',compress:true});
 const W=612,H=792,M=51,CW=W-2*M,BOTTOM=733;let y=0,page=1,headingNo=0;
 const rgb=hex=>hex.replace('#','').match(/../g).map(n=>parseInt(n,16));
 const orange=rgb(palette.orange),blue=rgb(palette.blue),blueText=rgb(palette.blueText),ink=rgb(palette.black);
 pdf.addFileToVFS('body.ttf',BriefAssets.fonts['ProximaNova-400']);pdf.addFont('body.ttf','Proxima','normal');
 pdf.addFileToVFS('bold.ttf',BriefAssets.fonts['ProximaNova-700']);pdf.addFont('bold.ttf','Proxima','bold');
 pdf.addFileToVFS('display.ttf',BriefAssets.fonts['Poppins-900']);pdf.addFont('display.ttf','Poppins','bold');
 pdf.addFileToVFS('medium.ttf',BriefAssets.fonts['Poppins-500']);pdf.addFont('medium.ttf','Poppins','normal');
 pdf.addFileToVFS('fallback.ttf',BriefAssets.fonts.NotoSans);pdf.addFont('fallback.ttf','Noto','normal');
 const supported=new Set(BriefAssets.coverage.NotoSans);
 const missing=[...new Set([...project.meta.title,...project.meta.client,...project.blocks.flatMap(b=>[...BriefStudio.textOf(b.html)])].filter(c=>!supported.has(c.codePointAt(0))&&!/[\n\r\t]/.test(c)))];
 if(missing.length)throw new Error('The supplied fonts do not support these characters: '+missing.slice(0,12).join(' ') + '. Use the HTML Print / Save PDF option for system font fallback.');
 pdf.setProperties({title:project.meta.title,subject:project.meta.label,author:'Impossible Outcomes',creator:'Impossible Brief Studio'});
 const markPath=new DOMParser().parseFromString(BriefAssets.mark,'image/svg+xml').querySelector('path').getAttribute('d');
 function markAt(x,y,size){const toks=markPath.match(/[a-zA-Z]|[-+]?(?:\d*\.)?\d+(?:e[-+]?\d+)?/g);let i=0,cmd='',px=0,py=0,sx=0,sy=0;const ops=[],k=size/4608.5;const pt=(a,b)=>[x+a*k,y+b*k];while(i<toks.length){if(/^[a-z]$/i.test(toks[i]))cmd=toks[i++];const rel=cmd===cmd.toLowerCase(),c=cmd.toUpperCase();if(c==='Z'){ops.push({op:'h',c:[]});px=sx;py=sy;cmd='';continue}const num=()=>Number(toks[i++]);if(c==='M'||c==='L'){let a=num(),b=num();if(rel){a+=px;b+=py}ops.push({op:c==='M'?'m':'l',c:pt(a,b)});px=a;py=b;if(c==='M'){sx=a;sy=b;cmd=rel?'l':'L'}}else if(c==='C'){let a=num(),b=num(),d=num(),e=num(),f=num(),g=num();if(rel){a+=px;b+=py;d+=px;e+=py;f+=px;g+=py}ops.push({op:'c',c:[...pt(a,b),...pt(d,e),...pt(f,g)]});px=f;py=g}else throw new Error('Unsupported mark path command '+cmd)}pdf.setFillColor(...rgb(palette.black));pdf.path(ops);pdf.fillEvenOdd()}
 const font=(weight='normal',size=11)=>{pdf.setFont('Proxima',weight);pdf.setFontSize(size);pdf.setTextColor(...ink)};
 const line=(x1,y1,x2,y2,color=[200,200,197],width=.5)=>{pdf.setDrawColor(...color);pdf.setLineWidth(width);pdf.line(x1,y1,x2,y2)};
 function footer(){font('normal',7.5);pdf.setTextColor(85,85,85);line(M,750,W-M,750);pdf.text('IMPOSSIBLE OUTCOMES',M,766);pdf.text(String(page).padStart(2,'0'),W-M,766,{align:'right'})}
 function nextPage(){footer();pdf.addPage();page++;markAt(M,30,19);font('bold',8);pdf.text(pdf.splitTextToSize(project.meta.title.replace(/\n/g,' '),CW-65)[0],M+31,42);line(M,60,W-M,60);y=85}
 function ensure(height){if(y+height>BOTTOM)nextPage()}
 function runs(html){const root=new DOMParser().parseFromString(html,'text/html').body;const out=[];function walk(n,bold=false,link=''){if(n.nodeType===3){const cm=new Set(BriefAssets.coverage[bold?'ProximaNova-700':'ProximaNova-400']);let text='',fallback=null;for(const c of n.textContent.replace(/\u00a0/g,' ')){const f=!cm.has(c.codePointAt(0))&&c!=='\n';if(f!==fallback&&text){out.push({text,bold,link,fallback});text=''}fallback=f;text+=c}if(text)out.push({text,bold,link,fallback});return}if(n.nodeType!==1)return;if(n.tagName==='BR'){out.push({text:'\n',bold,link});return}const b=bold||['STRONG','B','TH'].includes(n.tagName),u=n.tagName==='A'?n.getAttribute('href')||link:link;[...n.childNodes].forEach(c=>walk(c,b,u));if(['P','DIV'].includes(n.tagName))out.push({text:'\n',bold,link})}walk(root);return out}
 function plainRuns(text,family='Proxima',weight='normal'){
  const key=family==='Poppins'?(weight==='bold'?'Poppins-900':'Poppins-500'):(weight==='bold'?'ProximaNova-700':'ProximaNova-400');const cm=new Set(BriefAssets.coverage[key]);const out=[];let t='',fallback=null;
  for(const c of text){const f=!cm.has(c.codePointAt(0))&&c!=='\n';if(f!==fallback&&t){out.push({text:t,bold:weight==='bold',family,fallback});t=''}fallback=f;t+=c}if(t)out.push({text:t,bold:weight==='bold',family,fallback});return out;
 }
 function wrapRuns(rs,width,size){const lines=[];let current=[],x=0;function flush(){lines.push(current);current=[];x=0}for(const run of rs){for(const tok of run.text.split(/(\n|[^\S\n]+)/).filter(s=>s!=='')){if(tok==='\n'){flush();continue}font(run.bold?'bold':'normal',size);if(run.family)pdf.setFont(run.family,run.bold?'bold':'normal');if(run.fallback)pdf.setFont('Noto','normal');let w=pdf.getTextWidth(tok);if(x+w>width&&current.length&&tok.trim())flush();if(!current.length&&!tok.trim())continue;if(w>width){for(const char of tok){font(run.bold?'bold':'normal',size);if(run.family)pdf.setFont(run.family,run.bold?'bold':'normal');if(run.fallback)pdf.setFont('Noto','normal');const cw=pdf.getTextWidth(char);if(x+cw>width&&current.length)flush();current.push({...run,text:char,width:cw});x+=cw}}else{current.push({...run,text:tok,width:w});x+=w}}}if(current.length)flush();return lines}
 function drawLines(lines,x=M,width=CW,size=11,leading=16){for(let i=0;i<lines.length;i++){ensure(leading);let xx=x;for(const r of lines[i]){font(r.bold?'bold':'normal',size);if(r.family)pdf.setFont(r.family,r.bold?'bold':'normal');if(r.fallback)pdf.setFont('Noto','normal');if(r.link)pdf.setTextColor(...blueText);pdf.text(r.text,xx,y);if(r.link)pdf.link(xx,y-size,r.width,leading,{url:r.link});xx+=r.width}y+=leading}}
 function labelAt(text,x,baseline,size=9,bold=false,align='left',width=CW){const ls=wrapRuns(plainRuns(String(text),'Proxima',bold?'bold':'normal'),width,size);const oldY=y;y=baseline;for(const l of ls){const w=l.reduce((sum,r)=>sum+r.width,0);drawLines([l],align==='right'?x-w:x,width,size,size*1.3)}y=oldY;return Math.max(1,ls.length)*size*1.3}
 function paragraph(html,indent=0,size=11,leading=16){const ls=wrapRuns(runs(html),CW-indent,size);if(ls.length>1)ensure(Math.min(3,ls.length)*leading);drawLines(ls,M+indent,CW-indent,size,leading);y+=7}
 function list(html){const root=new DOMParser().parseFromString(html,'text/html').body;function walkList(el,depth=0){let number=Number(el.getAttribute('start'))||1;for(const li of [...el.children].filter(e=>e.tagName==='LI')){const clone=li.cloneNode(true);clone.querySelectorAll('ul,ol').forEach(n=>n.remove());const indent=18+depth*15,ls=wrapRuns(runs(clone.innerHTML),CW-indent,11);ensure(Math.min(2,ls.length)*16);font('normal',11);if(el.tagName==='OL')pdf.text(number+'.',M+depth*15,y);else{pdf.setFillColor(20,20,20);pdf.circle(M+depth*15+2,y-4,1.5,'F')}drawLines(ls,M+indent,CW-indent,11,16);y+=4;for(const child of li.children)if(['UL','OL'].includes(child.tagName))walkList(child,depth+1);number++}}for(const el of root.children)if(['UL','OL'].includes(el.tagName))walkList(el);y+=7}
 function table(html){const root=new DOMParser().parseFromString(html,'text/html').body;const rows=[...root.querySelectorAll('tr')].map(r=>[...r.children].filter(c=>['TD','TH'].includes(c.tagName)));if(!rows.length)return;const cols=Math.max(...rows.map(r=>r.reduce((s,c)=>s+(Number(c.getAttribute('colspan'))||1),0))),colw=CW/cols,fs=9.5,lh=13.5,pad=7;
 for(let ri=0;ri<rows.length;ri++){const cells=rows[ri].map(c=>({span:Number(c.getAttribute('colspan'))||1,html:c.innerHTML}));const cellLines=cells.map(c=>wrapRuns(runs(ri===0?'<strong>'+c.html+'</strong>':c.html),colw*c.span-pad*2,fs));const n=Math.max(...cellLines.map(ls=>ls.length),1);let start=0;while(start<n){ensure(lh+pad*2);const capacity=Math.max(1,Math.floor((BOTTOM-y-pad*2)/lh)),take=Math.min(n-start,capacity),height=take*lh+pad*2;const top=y;if(ri===0){pdf.setFillColor(241,241,238);pdf.rect(M,top,CW,height,'F')}let x=M;for(let ci=0;ci<cells.length;ci++){y=top+pad+fs;const w=colw*cells[ci].span;drawLines(cellLines[ci].slice(start,start+take),x+pad,w-pad*2,fs,lh);x+=w}y=top+height;line(M,y,W-M,y);start+=take;if(start<n)nextPage()}}
 y+=15}
 async function image(html){const el=new DOMParser().parseFromString(html,'text/html').querySelector('img');if(!el)return;const img=new Image();img.src=el.src;await img.decode();const ratio=img.height/img.width,w=Math.min(CW,img.width),h=Math.min(580,w*ratio),actualW=h/ratio;ensure(h+18);pdf.addImage(img,'PNG',M,y,actualW,h);y+=h+16}
 // Cover establishes hierarchy without replacing the brief's first page with a decorative blank.
 markAt(M,43,30);font('bold',8);pdf.text('IMPOSSIBLE OUTCOMES',W-M,50,{align:'right'});labelAt(project.meta.label.toUpperCase(),W-M,64,8,true,'right',CW*.65);
 let titleSize=43;let titleLines=wrapRuns(plainRuns(project.meta.title,'Poppins','bold'),CW,titleSize);while(titleLines.length*titleSize>190&&titleSize>20){titleSize--;titleLines=wrapRuns(plainRuns(project.meta.title,'Poppins','bold'),CW,titleSize)}y=136;drawLines(titleLines,M,CW,titleSize,titleSize*1.06);y+=28-titleSize*1.06;line(M,y,W-M,y,[20,20,20],.7);y+=19;font('bold',9);const clientHeight=labelAt(project.meta.client,M,y,9,true,'left',CW*.62);const labelHeight=labelAt(project.meta.label,W-M,y,9,false,'right',CW*.33);y+=Math.max(clientHeight,labelHeight)+16;
 pdf.addImage(await BriefMaterial.image(),'PNG',M,y,CW,74);y+=95;
 for(const b of project.blocks){if(b.type==='heading'){headingNo++;ensure(78);y+=12;line(M,y,W-M,y);y+=27;font('bold',8);pdf.setTextColor(...blueText);pdf.text(String(headingNo).padStart(2,'0'),M,y-1);pdf.setFont('Poppins','normal');pdf.setFontSize(b.level>2?14:17);pdf.setTextColor(...ink);const heading=wrapRuns(plainRuns(BriefStudio.textOf(b.html),'Poppins','normal'),CW-32,b.level>2?14:17);drawLines(heading,M+32,CW-32,b.level>2?14:17,b.level>2?17:21);y+=6}else if(b.type==='list')list(b.html);else if(b.type==='table')table(b.html);else if(b.type==='image')await image(b.html);else if(b.type==='quote'){ensure(40);const startY=y,ls=wrapRuns(runs(b.html),CW-23,14);drawLines(ls,M+23,CW-23,14,20);if(y>startY)line(M,startY-12,M,y-5,orange,3);y+=12}else paragraph(b.html)}
 if(project.source.url){ensure(52);y+=14;line(M,y,W-M,y);y+=20;font('bold',9);pdf.setTextColor(...blueText);pdf.textWithLink('Source brief',M,y,{url:project.source.url});y+=15}
 footer();pdf.save(slug+'-brief.pdf');return pdf;
}};
