(()=>{'use strict';
const e=(s,cls='',tag='div')=>`<${tag} class="${cls}" contenteditable="plaintext-only" spellcheck="false">${s}</${tag}>`;
const mark='<span class="mark" aria-label="Impossible Outcomes mark"></span>',word='<span class="wordmark" aria-label="The Impossible Outcomes Co."></span>';
const mat=(mode='field',preset='prism',extra='')=>`<canvas class="material" data-material="${mode}" data-preset="${preset}" ${extra} aria-label="${mode} material"></canvas>`;
const top=(right='IMPOSSIBLE OUTCOMES')=>`<div class="page-top">${mark}${e(right,'label')}</div>`;
const foot=(left='STRATEGY / SYSTEMS / DESIGN / INTELLIGENCE',right='IMPOSSIBLEOUTCOMES.CO')=>`<div class="page-bottom">${e(left,'label')}${e(right,'label')}</div>`;
const status='<div class="phone-status"><span>9:41</span><span>▰ ▰</span></div>';
const defs=`<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs><filter id="ink-texture" x="-4%" y="-5%" width="108%" height="112%" color-interpolation-filters="sRGB"><feTurbulence type="fractalNoise" baseFrequency=".72" numOctaves="2" seed="29" result="grain"/><feColorMatrix in="grain" type="saturate" values="0"/><feComponentTransfer><feFuncR type="linear" slope=".55" intercept=".225"/><feFuncG type="linear" slope=".55" intercept=".225"/><feFuncB type="linear" slope=".55" intercept=".225"/></feComponentTransfer><feComposite in2="SourceGraphic" operator="in" result="ink"/><feBlend in="SourceGraphic" in2="ink" mode="soft-light" result="rough"/><feTurbulence baseFrequency=".013 .09" numOctaves="2" seed="12" result="edge"/><feDisplacementMap in="rough" in2="edge" scale="1.1" xChannelSelector="R" yChannelSelector="G"/><feDropShadow dx="-1.4" dy="2" stdDeviation=".25" flood-color="#0D1C43" flood-opacity=".75"/></filter><pattern id="print-dots" width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(24)"><rect width="5" height="5" fill="white"/><circle cx="2" cy="2" r=".64" fill="#888"/></pattern><mask id="ink-screen"><rect width="2000" height="2000" fill="url(#print-dots)"/></mask></defs></svg>`;
/* Brand copy and editable application examples. */
const principles=[['001','Passion','Do what you want and you’ll find you’ve done what you must.'],['002','Resolve','Don’t compromise.'],['003','Adaptability','There are many ways to be right and one way to be wrong.'],['004','Outcome','We work for the outcome.']];
const caps=[['01','Marketing &<br>creative','Brand identity<br>Brand & campaign strategy<br>Content creation<br>Brand experience'],['02','Ventures &<br>innovation','Product development<br>Business consultancy<br>Brand licensing + IP<br>Research & development'],['03','Technology &<br>R&D','UX research & strategy<br>UI design<br>Website development<br>Application builds'],['04','Studios &<br>storytelling','Story & narrative development<br>Publishing & licensing<br>Sourcing IP & securing rights<br>Talent outreach']];
const apps=[
/* ---- Campaign ---- */
{id:'campaign',name:'Poster / folded field',format:'Poster · 900 × 1200',w:900,h:1200,class:'campaign',material:'fold',register:'Showcase',rule:'One statement in the reserve of the fold. Type sits on a solid black panel; the fold retains full color above it.',body:mat('fold','prism','data-grain=".07" data-seed=".62" data-rotation="-.9"')+top('BRAND & CREATIVE SYSTEMS')+`<div class="headline">${e('Turning<br>complexity<br>into real-world<br>outcomes.','display')}</div>`+foot('THE IMPOSSIBLE<br>OUTCOMES CO.','STRATEGY<br>SYSTEMS<br>DESIGN<br>INTELLIGENCE'),color:'white'},
{id:'resolve',name:'Poster / solid ember',format:'Poster · 900 × 1200',w:900,h:1200,class:'poster-grid',register:'Showcase',rule:'Full-strength ember at 100%. The mark is the only other element; scale it independently of the headline.',body:`<div class="label">IMPOSSIBLE OUTCOMES / 002 RESOLVE</div><div style="margin-top:135px">${e('Don’t<br>compro-<br>mise.','display big')}</div>${mark}<div class="poster-meta">${e('We work for<br>the outcome.','voice')}<div class="rule"></div><div class="label">STRATEGY / SYSTEMS / DESIGN</div></div>`},
{id:'series',name:'Poster series / three materials',format:'Series · 1600 × 900',w:1600,h:900,class:'series',register:'Showcase',rule:'Same type position, same mark position, three different materials. The system is the constant; the material is the variable.',body:`<div class="series-row">${[['eclipse','Create the<br>conditions.','01 / FOCUS','data-grain=".06"'],['ribbon','Then make<br>it real.','02 / MOTION','data-grain=".08" data-rotation="-.75"'],['orb','We work for<br>the outcome.','03 / SYSTEMS','data-grain=".08" data-seed=".41"']].map(([m,t,l,x])=>`<div class="poster">${mat(m,'prism',x)}<div class="page-top">${mark}${e(l,'label')}</div>${e(t,'display')}${e('THE IMPOSSIBLE OUTCOMES CO.','label foot')}</div>`).join('')}</div><div class="series-caption"><span class="label">CAMPAIGN SET / 01–03</span><span class="label">ONE SYSTEM · THREE MATERIALS</span></div>`},
{id:'ooh',name:'Out-of-home / landscape',format:'Billboard · 1600 × 600',w:1600,h:600,class:'ooh',register:'Showcase',rule:'A statement at the left, a body at the right. Read distance is long: one line, no small copy except the signature.',body:mat('orb','prism','data-grain=".07" data-seed=".77"')+`<div class="ooh-copy">${e('Not an agency.<br>Not a lab.<br>Not a studio.','display')}${e('The Impossible Outcomes Co.','voice')}</div>${mark}<div class="ooh-side label">STRATEGY / SYSTEMS / DESIGN / INTELLIGENCE</div>`,color:'white'},
{id:'typeposter',name:'Type poster / line screen',format:'Poster · 900 × 1200',w:900,h:1200,class:'typeposter',register:'Showcase',rule:'Paper, one ink, one pitch. The screen carries the field; the black type carries the message.',body:`<div class="screen-band">${mat('lines','prism','data-grain=".03" data-rotation="-.35" data-scale="2.2" data-offset=".3"')}</div>${top('IMPOSSIBLE OUTCOMES / TYPE STUDY')}<div class="type-block">${e('Keep the<br>signal.','display')}${e('Change the form.','voice')}</div><div class="type-meta">${e('Poppins Black 900 · −0.04em · 0.92','label')}${e('Fixed pitch · Solar Ember ink','label')}</div>`+foot('THE IMPOSSIBLE OUTCOMES CO.','STRATEGY / SYSTEMS / DESIGN / INTELLIGENCE')},
{id:'hello',name:'Brand / textured Hello',format:'Landscape · 1500 × 1000',w:1500,h:1000,class:'hello-template',register:'Showcase',rule:'Grain in the ink, a separate field behind it. The word stays live SVG text; edit it in the text field.',body:mat('field','prism','data-grain=".055" data-size=".62" data-offset=".29" data-spread="5"')+top('IMPOSSIBLE OUTCOMES / HELLO, WØRLD')+`<svg class="hello-art" viewBox="0 0 1500 850" xmlns="http://www.w3.org/2000/svg"><text x="93" y="470" filter="url(#ink-texture)" mask="url(#ink-screen)" data-svg-edit="true">Hello.</text><text x="100" y="595" class="hello-sub" data-svg-edit="true">Create the conditions.</text></svg>`+foot('THE IMPOSSIBLE OUTCOMES CO.','STRATEGY / SYSTEMS / DESIGN / INTELLIGENCE')},
/* ---- Social ---- */
{id:'story',name:'Social / story',format:'Phone · story composition',w:1200,h:820,class:'device-scene',material:'ribbon',register:'Showcase',rule:'Interface chrome stays quiet. Headline inside the safe area; the bottom band belongs to the mark and the action.',body:`<div class="phone"><div class="phone-screen story">${mat('ribbon','prism','data-grain=".08" data-rotation="-1.25"')}${status}<div class="story-top"><div class="story-progress"></div>impossibleoutcomes</div>${e('Create the<br>conditions.','display')}${mark}<div class="story-bottom">Discover Impossible ↗</div></div></div><div class="device-caption"><div class="label">01 / STORY</div>${e('One clear<br>invitation.','display')}<p>Large type.<br>A live material.<br>A direct next step.</p></div>`},
{id:'feed',name:'Social / feed',format:'Phone · square composition',w:1200,h:820,class:'device-scene',register:'Showcase',rule:'The message reads at thumbnail size. Interface and caption stay outside the artwork.',body:`<div class="device-caption"><div class="label">02 / FEED</div>${e('The idea<br>travels.','display')}<p>A square artwork with the same type, material, and mark.</p></div><div class="phone"><div class="phone-screen feed-screen">${status}<div class="feed-bar">${mark}<b>impossibleoutcomes</b><span style="margin-left:auto">•••</span></div><div class="feed-image">${mat('eclipse','prism','data-grain=".06"')}${e('We work<br>for the<br>outcome.','display')}</div><div class="feed-copy"><div class="icons"><span>♡</span><span>○</span><span>↗</span></div><b>impossibleoutcomes</b>${e('Strategy, systems, design, intelligence. Creating the conditions for real-world outcomes.','copy')}<div style="color:#777;margin-top:20px">View profile ↗</div></div></div></div>`},
{id:'carousel',name:'Social / carousel',format:'Carousel · 1600 × 620',w:1600,h:620,class:'carousel',register:'Showcase',rule:'Three frames, one idea. Material → solid → paper: the sequence moves from atmosphere to statement to detail.',body:`<div class="tiles"><div class="tile">${mat('fold','prism','data-grain=".07" data-seed=".2" data-scale="9"')}${e('Create the<br>conditions.','display')}<span class="label idx">1 / 3</span></div><div class="tile solid">${e('Then<br>make it<br>real.','display')}${mark}<span class="label idx">2 / 3</span></div><div class="tile paper">${mat('thermal','prism','data-grain=".08" data-seed=".9"')}<div class="tile-copy">${e('Strategy. Systems.<br>Design. Intelligence.','voice')}${e('The Impossible Outcomes Co.','label')}</div><span class="label idx">3 / 3</span></div></div>`},
{id:'profile',name:'Social / profile',format:'Tablet · six-post system',w:1200,h:800,class:'profile',register:'Showcase',rule:'Vary material and scale; repeat the type hierarchy and the mark position across the grid.',body:`<div class="tablet"><div class="tablet-screen"><div class="profile-header">${mark}<div><strong>impossibleoutcomes</strong>${e('Strategy / Systems / Design / Intelligence')}<p>New York · impossibleoutcomes.co</p></div></div><div class="profile-grid"><div class="profile-tile">${mat('fold','prism','data-grain=".07"')}${e('Turning<br>complexity.','display')}</div><div class="profile-tile orange">${e('Don’t<br>compro-<br>mise.','display')}${mark}</div><div class="profile-tile">${mat('orb','prism','data-seed=".3"')}${mark}</div><div class="profile-tile white">${e('Create the<br>conditions.','voice')}${mark}</div><div class="profile-tile">${mat('chrome','prism','data-rotation="-.9"')}${mark}</div><div class="profile-tile">${mat('edge','prism')}${e('Real-world<br>outcomes.','display')}</div></div></div></div>`},
/* ---- Presentation ---- */
{id:'deck',name:'Deck / opening',format:'Presentation · 1600 × 900',w:1600,h:900,class:'deck',material:'chrome',register:'Showcase',rule:'16:9, one central statement. The tube crosses the frame once and the rail carries context, never a paragraph.',body:mat('chrome','prism','data-grain=".05" data-rotation="-.35" data-seed=".8" data-offset="-.3"')+top('THE IMPOSSIBLE OUTCOMES CO.')+`<div class="deck-title">${e('Create the<br>conditions.','display')}${e('Strategy. Systems. Design. Intelligence.','voice')}</div><div class="deck-rail"><span>CAPABILITIES</span><span>IMPOSSIBLE OUTCOMES</span><span>01</span></div>`},
{id:'divider',name:'Deck / section divider',format:'Presentation · 1600 × 900',w:1600,h:900,class:'divider',register:'Showcase',rule:'A number, a title, a body. The eclipse is the counter-form; nothing else competes with it.',body:mat('eclipse','prism','data-grain=".06"')+top('THE IMPOSSIBLE OUTCOMES CO.')+`<div class="divider-copy">${e('02','number')}${e('How we<br>work.','display')}${e('Conditions before ideas.','voice')}</div><div class="deck-rail"><span>SECTION 02 / 05</span><span>IMPOSSIBLE OUTCOMES</span><span>14</span></div>`,color:'white'},
{id:'capabilities',name:'Deck / capabilities',format:'Presentation · 1600 × 900',w:1600,h:900,class:'capabilities',register:'Workshop',rule:'Four comparable groups. Rules and white space first; illustration only if it adds evidence.',body:top('CAPABILITIES / 02')+e('From strategy to the thing itself.','display')+`<div class="cap-grid">${caps.map(a=>`<div><span class="label" style="color:var(--blue-soft)">${a[0]}</span>${e(a[1],'','h3')}${e(a[2],'','p')}</div>`).join('')}</div>`+foot('THE IMPOSSIBLE OUTCOMES CO.','STRATEGY / SYSTEMS / DESIGN / INTELLIGENCE')},
{id:'diagram',name:'Strategy / amplification',format:'Diagram · 1200 × 750',w:1200,h:750,class:'diagram',register:'Workshop',rule:'Every node has a role. The path back to the central outcome stays visible; color distinguishes channels.',body:top('STRATEGY / AMPLIFICATION')+e('Amplify the experience.','display')+`<svg class="diagram-art" viewBox="0 0 950 390" role="img" aria-label="Event amplification channels"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="none" stroke="#3D6DF4"/></marker></defs><g fill="none" stroke="#3D6DF4" stroke-width="1.6" marker-end="url(#arrow)"><path d="M395 160C350 110 345 90 310 90"/><path d="M555 160C600 110 630 90 665 90"/><path d="M395 230C350 275 345 290 310 290"/><path d="M555 230C600 275 630 290 665 290"/></g><circle cx="475" cy="195" r="102" fill="#F46138"/><text x="475" y="175" text-anchor="middle" font-size="23" font-weight="700"><tspan x="475">Special Delivery</tspan><tspan x="475" dy="28">Events</tspan></text><text x="475" y="239" text-anchor="middle" font-size="12">CENTRAL EXPERIENCE</text>${[[25,45,'01','Owned + boosted social','Publish, amplify, recirculate'],[690,45,'02','Influencer','Extend the experience'],[25,290,'03','Earned media + PR','Create a reason to cover it'],[690,290,'04','Recipients','Enable people to share']].map(([x,y,n,t,s])=>`<g transform="translate(${x} ${y})"><text font-size="12" fill="#000000">${n}</text><text y="28" font-size="21" font-weight="700">${t}</text><text y="52" font-size="15">${s}</text></g>`).join('')}</svg><div class="diagram-foot"><span>APPLICATION: EVENT AMPLIFICATION PLAN</span><span>EXPERIENCE → PARTICIPATION → AMPLIFICATION</span></div>`},
/* ---- Documents ---- */
{id:'cover',name:'Document / report cover',format:'Portrait · 850 × 1100',w:850,h:1100,class:'cover',register:'Workshop',rule:'The screen is the cover; the title block is solid. Nothing sits over the halftone except the mark.',body:mat('screen','prism','data-grain=".04" data-scale="4.6" data-seed=".25"')+`<div class="cover-top">${mark}${e('IMPOSSIBLE OUTCOMES','label')}</div><div class="cover-block">${e('Keep the signal.<br>Change the form.','display')}<div class="cover-row">${e('We work for the outcome.','voice')}${e('STRATEGY / SYSTEMS / DESIGN / INTELLIGENCE','label')}</div></div>`},
{id:'spread',name:'Editorial / spread',format:'Spread · 1600 × 1000',w:1600,h:1000,class:'spread',register:'Workshop',rule:'Left page is the material, right page is the argument. Body text never crosses the gutter; folios sit on the outer corners.',body:`<div class="page left">${mat('thermal','prism','data-grain=".08" data-seed=".5"')}<span class="folio label">12</span></div><div class="page right"><div class="kicker">${e('02 / PRINCIPLES','label')}${e('THE IMPOSSIBLE OUTCOMES CO.','label')}</div>${e('There are many<br>ways to be right<br>and one way<br>to be wrong.','display')}<div class="columns">${e('We don’t create ideas. We create conditions for outcomes. The work begins by refusing a domain’s surface presentation and building the instrument that exposes its actual logic.','','p')}${e('Four principles hold the practice together: passion, resolve, adaptability, outcome. Each one is a constraint on how a decision gets made, not a slogan on a wall.','','p')}</div><div class="principle-list">${principles.map(([n,t,s])=>`<div><span class="label">${n}</span>${e(t,'','strong')}${e(s,'','p')}</div>`).join('')}</div><span class="folio label">13</span></div>`},
{id:'brief',name:'Document / working brief',format:'Portrait · 850 × 1100',w:850,h:1100,class:'brief',register:'Workshop',rule:'Write the decision before the detail. Owner, constraints, source of truth, and acceptance stay visible.',body:`<div style="display:flex;justify-content:space-between">${mark}<span class="label">WORKING BRIEF / 01</span></div>${e('Working<br>principles.','display')}${e('Strategy. Systems. Design. Intelligence.','brief-intro')}<div class="brief-grid">${[['THE IDEA','We don’t create ideas. We create conditions for outcomes.'],['PRACTICE','Strategy. Systems. Design. Intelligence.'],['PASSION','Do what you want and you’ll find you’ve done what you must.'],['RESOLVE','Don’t compromise.'],['ADAPTABILITY','There are many ways to be right and one way to be wrong.'],['OUTCOME','We work for the outcome.']].map(([h,p])=>`<div><h3 class="label">${h}</h3>${e(p,'','p')}</div>`).join('')}</div><div class="brief-foot"><span>THE IMPOSSIBLE OUTCOMES CO.</span><span>IMPOSSIBLE OUTCOMES / PRINCIPLES</span></div>`},
{id:'report',name:'Document / evidence spread',format:'Landscape · 1400 × 900',w:1400,h:900,class:'report',register:'Workshop',rule:'Separate the evidence from the interpretation. The visual supports the finding; it never stands in for it.',body:top('SYSTEM REVIEW / 01')+`<div class="report-grid"><div>${e('Keep the signal.<br>Change the form.','display')}${e('The material can vary. The brand anchors stay fixed.','voice')}<div class="evidence"><div class="label" style="color:var(--blue-soft)">01 / OBSERVED</div>${e('The mark, typography, and palette establish a consistent visual signature.','report-detail')}</div><div class="evidence"><div class="label" style="color:var(--blue-soft)">02 / APPLICATION</div>${e('Keep the mark intact and the type hierarchy clear across formats.','report-detail')}</div></div><div><div class="report-visual">${mat('fold','prism','data-grain=".07" data-seed=".35"')}${mark}</div><p class="report-detail">FOLDED FIELD / EMBER + VIOLET<br>A pressed surface with one raking light.</p></div></div>`+foot('IMPOSSIBLE OUTCOMES / BRAND ELEMENTS','THE IMPOSSIBLE OUTCOMES CO.')},
{id:'stationery',name:'Print / correspondence',format:'Business card + letterhead',w:1200,h:760,class:'stationery',register:'Workshop',rule:'Physical framing is presentation only. Card and letterhead are flat, editable layouts with exact marks.',body:`<div class="business-card">${word}<div class="card-foot">${e('Strategy / Systems / Design / Intelligence')}<div class="label" style="font-size:9px;margin-top:25px">STRATEGY / SYSTEMS / DESIGN / INTELLIGENCE</div></div></div><div class="letterhead">${mark}${e('Create the<br>conditions.','display')}${e('Strategy, systems, design, intelligence.<br><br>Turning complexity into real-world outcomes.','','p')}<div class="letter-foot">THE IMPOSSIBLE OUTCOMES CO.<br>Strategy / Systems / Design / Intelligence</div></div>`},
/* ---- Web, product, motion ---- */
{id:'web',name:'Website / hero',format:'Desktop · 1440 × 900',w:1440,h:900,class:'web',preset:'site',register:'Showcase',rule:'Navigation and text stay in the DOM. The lens refracts the field; it never obstructs editing.',body:mat('field','site','data-lens="true" data-reserve="left" data-offset=".62"')+`<div class="web-nav">${mark}<nav><span>What we do</span><span>How we work</span><span>Get in touch ↗</span></nav><span class="label">THE IMPOSSIBLE<br>OUTCOMES CO.</span></div><div class="web-title">${e('Turning complexity','display')}${e('into real-world','voice')}${e('outcomes.','display')}</div><div class="web-bottom">${e('Not an agency.<br>Not a lab. Not a studio.')}<span class="label">STRATEGY / SYSTEMS / DESIGN / INTELLIGENCE</span></div>`,color:'white'},
{id:'app',name:'Product / app screen',format:'Phone · dark interface',w:1200,h:820,class:'device-scene',register:'Workshop',rule:'Material only in the header band. Lists, controls and small type sit on a stable dark surface with subtle dividers.',body:`<div class="device-caption"><div class="label">03 / PRODUCT</div>${e('The system<br>in use.','display')}<p>One material band.<br>Stable surfaces below.<br>Nothing decorative.</p></div><div class="phone"><div class="phone-screen app-screen">${status}<div class="app-header">${mat('edge','prism','data-grain=".05" data-rotation="-.2"')}<div class="app-header-copy">${e('Outcomes','display')}${e('Work / overview','label')}</div></div><div class="app-list">${[['01','Brand system','In review','ember'],['02','Product launch','Active','sky'],['03','Research sprint','Active','violet'],['04','Story platform','Active','ember'],['05','Ventures brief','Draft','pale']].map(([n,t,s,c])=>`<div class="app-row"><span class="dot ${c}"></span><div>${e(t,'','strong')}${e(s,'','span')}</div><span class="label">${n}</span></div>`).join('')}</div><div class="app-tab"><span class="on">Work</span><span>Approach</span><span>Capabilities</span><span>Contact</span></div></div></div>`},
{id:'film',name:'Motion / title frame',format:'Film · 1600 × 900',w:1600,h:900,class:'film',material:'edge',register:'Showcase',rule:'The light moves slowly behind stationary, legible type. Respect reduced motion and provide a pause control.',body:mat('edge','prism','data-grain=".06" data-live="true" data-rotation="-.28"')+`<div class="film-title">${e('Real-world<br>outcomes.','display')}${e('The Impossible Outcomes Co.','voice')}</div>${mark}<div class="timecode">00:00:04:12</div>`}
];
window.IOApplications=apps;window.IODefs=defs;window.IOMark=mark;window.IOWord=word;window.IOMaterial=mat;
})();
