/* Shared WebGL field renderer. Original field math is preserved in source/site-field.frag. */
(() => {'use strict';
const T=window.IOTokens,C=['black','navy','blue','blueSoft','bluePale','terracotta','orange','white'].map(k=>T.colors[k]),budget=T.performance;
const rgb=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255);
const lab=h=>{let[r,g,b]=rgb(h).map(v=>v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4));let l=Math.cbrt(.4122214708*r+.5363325363*g+.0514459929*b),m=Math.cbrt(.2119034982*r+.6806995451*g+.1073969566*b),s=Math.cbrt(.0883024619*r+.2817188376*g+.6299787005*b);return[.2104542553*l+.793617785*m-.0040720468*s,1.9779984951*l-2.428592205*m+.4505937099*s,.0259040371*l+.7827717662*m-.808675766*s]};
// Static fallback uses the same color path; its geometry is a simple diagonal.
function fallbackRGB(d,t){
 const mix=(a,b,f)=>a.map((v,i)=>v+(b[i]-v)*f),smooth=(a,b,v)=>{v=Math.max(0,Math.min(1,(v-a)/(b-a)));return v*v*(3-2*v)},st=d.colors.map(i=>lab(C[i])),bridge=mix(st[1],st[2],.12);
 let a,b,f;if(t<.28){a=st[0];b=st[1];f=t/.28}else if(t<.38){a=st[1];b=bridge;f=(t-.28)/.10}else if(t<.54){a=bridge;b=st[3];f=(t-.38)/.16}else{a=st[3];b=st[4];f=(t-.54)/.46}
 const w=Math.max(.25,Math.min(1,d.size));f=smooth(.5-w*.5,.5+w*.5,f);let [L,A,B]=mix(a,b,f);const sh=Math.sin(f*Math.PI),angle=(-.72*smooth(.018,.075,-B)-.42*smooth(.028,.115,A))*sh*smooth(.10,.30,Math.abs(a[0]-b[0]));const aa=(Math.cos(angle)*A-Math.sin(angle)*B)*(1+.14*sh),bb=(Math.sin(angle)*A+Math.cos(angle)*B)*(1+.14*sh);if(t>=.38&&t<.54)L-=.045*sh;
 const l=(L+.3963377774*aa+.2158037573*bb)**3,m=(L-.1055613458*aa-.0638541728*bb)**3,z=(L-.0894841775*aa-1.291485548*bb)**3;
 return 'rgb('+[4.0767416621*l-3.3077115913*m+.2309699292*z,-1.2684380046*l+2.6097574011*m-.3413193965*z,-.0041960863*l-.7034186147*m+1.707614701*z].map(v=>Math.round(255*Math.max(0,Math.min(1,v<=.0031308?12.92*v:1.055*Math.max(0,v)**(1/2.4)-.055)))).join(',')+')';
}
const source=window.FIELD_SOURCE,material=window.MATERIAL_SOURCE;
const MODES={fold:1,eclipse:2,orb:3,edge:4,ribbon:5,screen:6,chrome:7,thermal:8,lines:9};
/* grain gain per material: print surfaces carry more tooth, optical bodies less */
const GRAIN={fold:1.0,eclipse:1.0,orb:.9,edge:1.7,ribbon:2.6,screen:1.6,chrome:1.6,thermal:1.5,lines:.4};
const DEFAULTS={fold:{scale:17,rotation:-.55,displace:3.4,offset:.1},eclipse:{scale:1,rotation:0,displace:2.4,offset:0},orb:{scale:1,rotation:0,displace:2.4,offset:0},edge:{scale:1,rotation:-.35,displace:2.4,offset:0},ribbon:{scale:1,rotation:-.42,displace:2.4,offset:0},screen:{scale:1,rotation:0,displace:2.4,offset:0},chrome:{scale:1,rotation:-.62,displace:2.4,offset:0},thermal:{scale:1,rotation:0,displace:2.4,offset:0},lines:{scale:3,rotation:-.55,displace:2.6,offset:.1}};
const off=document.createElement('canvas'),gl=off.getContext('webgl',{alpha:false,preserveDrawingBuffer:true,antialias:false});
let programs=[],failure=gl?'':'WebGL unavailable; static fallback active.';
function program(fs){const p=gl.createProgram();for(const[type,s]of[[gl.VERTEX_SHADER,'attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}'],[gl.FRAGMENT_SHADER,fs]]){const sh=gl.createShader(type);gl.shaderSource(sh,s);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));gl.attachShader(p,sh)}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return{p,u:new Map()}}
if(gl)try{programs=[program(source),material?program(material):null];const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW)}catch(e){failure=e.message;console.error(e)}
/* the hero ramp: black, navy, sky, ember, black — it opens and closes on the void */
const presets={site:{colors:[0,1,2,6,0],size:.75,displace:4.5,offset:.52,rotation:.3,spread:3.6},atmosphere:{colors:[0,1,2,6,0],size:.75,displace:4.5,offset:.52,rotation:.3,spread:3.6},blue:{colors:[0,1,3,2,0],size:.75,displace:4.5,offset:.62,rotation:.6,spread:3.6},orange:{colors:[0,5,6,5,0],size:.75,displace:4.5,offset:.03,rotation:-.45,spread:3.6},prism:{colors:[0,1,2,6,0],size:.75,displace:4.5,offset:.52,rotation:.3,spread:3.6}};
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let manualPaused=false,paused=reduced.matches,time=4,last=0,renderCount=0;const records=new Map();
function uniform(P,n,...v){let loc=P.u.get(n);if(loc===undefined){loc=gl.getUniformLocation(P.p,n);P.u.set(n,loc)}if(loc===null)return;if(v.length===3)gl.uniform3f(loc,...v);else if(v.length===2)gl.uniform2f(loc,...v);else gl.uniform1f(loc,v[0])}
function draw(c,t=4){const r=c.getBoundingClientRect();if(!r.width)return;const d=presets[c.dataset.preset||T.field.defaultPreset]||presets.prism,mode=c.dataset.material||'field';
 let w=Math.min(budget.maxDimension,Math.max(120,Math.round(r.width*Math.min(devicePixelRatio,budget.maxDpr)))),h=Math.max(80,Math.round(w*r.height/r.width));const cap=Math.min(1,budget.maxDimension/h,Math.sqrt(budget.maxPixels/(w*h)));w=Math.round(w*cap);h=Math.round(h*cap);if(c.width!==w||c.height!==h){c.width=w;c.height=h}const x=c.getContext('2d');
 if(!gl||failure||c.dataset.forceFallback==='true'){let g=x.createLinearGradient(0,h,w,0);for(let i=0;i<=64;i++)g.addColorStop(i/64,fallbackRGB(d,i/64));x.fillStyle=g;x.fillRect(0,0,w,h);if(c.dataset.reserve==='left'){const shade=x.createLinearGradient(0,0,w,0);shade.addColorStop(0,'rgba(0,0,0,.9)');shade.addColorStop(.3,'rgba(0,0,0,.85)');shade.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=shade;x.fillRect(0,0,w,h)}c.dataset.fallback='true';c.dataset.rendered='true';return}
 delete c.dataset.fallback;if(off.width!==w||off.height!==h){off.width=w;off.height=h}gl.viewport(0,0,w,h);const P=programs[mode==='field'?0:1]||programs[0];if(P===programs[0]&&mode!=='field')c.dataset.material='field';gl.useProgram(P.p);const pos=gl.getAttribLocation(P.p,'p');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);
 const mouse=records.get(c)?.mouse||[2,2];
 uniform(P,'uRes',w,h);uniform(P,'uTime',t);uniform(P,'uLens',...mouse);uniform(P,'uDrift',0,0);uniform(P,'uLensR',.145);uniform(P,'uLensS',c.dataset.lens? .030:0);uniform(P,'uRim',c.dataset.lens?.04:0);uniform(P,'uReserve',c.dataset.reserve==='left'?1:0);uniform(P,'uGrainFps',T.motion.grainFps);uniform(P,'uRateA',T.motion.fieldRates[0]);uniform(P,'uRateB',T.motion.fieldRates[1]);
 uniform(P,'uSize',Number(c.dataset.size||d.size));uniform(P,'uOffset',Number(c.dataset.offset||d.offset));uniform(P,'uRotation',d.rotation);uniform(P,'uSpread',Number(c.dataset.spread||d.spread||2.4));uniform(P,'uDisplace',d.displace);uniform(P,'uSeed',Number(c.dataset.seed||.3197));uniform(P,'uZoom',1.);uniform(P,'uSpacing',5.);uniform(P,'uGrain',Math.min(budget.maxGrain,Number(c.dataset.grain??.06)));
 if(mode==='field'){d.colors.forEach((v,i)=>uniform(P,'uC'+(i+1),...lab(C[v])))}else{const m=DEFAULTS[mode]||DEFAULTS.fold;uniform(P,'uMode',MODES[mode]||1);uniform(P,'uScale',Number(c.dataset.scale||m.scale));uniform(P,'uRotation',Number(c.dataset.rotation||m.rotation));uniform(P,'uDisplace',Number(c.dataset.displace||m.displace));uniform(P,'uOffset',Number(c.dataset.offset||m.offset));uniform(P,'uGrain',Math.min(budget.maxGrain,Number(c.dataset.grain??.06)*(GRAIN[mode]||1)));
  const palette=c.dataset.preset||'prism';const e=palette==='blue'?2:6,sky=palette==='orange'?6:2;uniform(P,'uE',...lab(C[e]));uniform(P,'uS',...lab(C[sky]));uniform(P,'uV',...lab(C[palette==='orange'?6:3]));uniform(P,'uN',...lab(C[1]));uniform(P,'uP',...lab(C[4]));uniform(P,'uEs',...lab(C[5]));uniform(P,'uW',...lab(C[7]));
  const ramp=c.dataset.preset==='blue'?[0,1,3,2,0]:c.dataset.preset==='orange'?[0,5,6,5,0]:[0,1,2,6,0];ramp.forEach((v,i)=>uniform(P,'uC'+(i+1),...lab(C[v])))}
 gl.drawArrays(gl.TRIANGLES,0,6);x.drawImage(off,0,0);c.dataset.rendered='true';renderCount++;
}
const io=new IntersectionObserver(items=>items.forEach(e=>{const r=records.get(e.target);if(r){r.visible=e.isIntersecting;if(r.visible)draw(e.target,time)}}),{rootMargin:'100px'});
function scan(root=document){root.querySelectorAll('canvas.material').forEach(c=>{if(records.has(c))return;records.set(c,{visible:false,mouse:[2,2]});io.observe(c);if(c.dataset.lens)c.parentElement.addEventListener('pointermove',e=>{const b=c.getBoundingClientRect(),min=Math.min(b.width,b.height);records.get(c).mouse=[(e.clientX-b.left-b.width/2)/min,(b.height/2-e.clientY+b.top)/min];if(paused&&!reduced.matches)draw(c,time)});draw(c,time)})}
function tick(ts){requestAnimationFrame(tick);if(document.hidden||ts-last<1000/budget.fieldFps)return;const dt=Math.min(.1,(ts-last)/1000);last=ts;if(!paused)time+=dt;let drawn=0;for(const[c,r]of records){if(!c.isConnected){io.unobserve(c);records.delete(c);continue}if(r.visible&&!paused&&((c.dataset.material||'field')==='field'||c.dataset.live)&&drawn++<budget.maxVisibleCanvases)draw(c,time)}}
window.IOEngine={scan,draw,presets,modes:MODES,defaults:DEFAULTS,capabilities:{field:["size","offset","seed"],fold:["scale","rotation","displace","offset","seed"],ribbon:["rotation","offset","seed"],eclipse:["seed"],orb:["seed"],chrome:["rotation","offset","seed"],thermal:["seed"],screen:["seed"],lines:["scale","rotation","displace","offset","seed"],edge:["rotation","seed"]},setPaused(v){manualPaused=Boolean(v);paused=manualPaused||reduced.matches},get paused(){return paused},get time(){return time},get error(){return failure},get stats(){return{contexts:gl?1:0,canvases:records.size,visible:[...records.values()].filter(r=>r.visible).length,renderCount,budget,reducedMotion:reduced.matches,hidden:document.hidden}},redraw(){for(const[c,r]of records)if(r.visible)draw(c,time)}};
addEventListener('resize',()=>IOEngine.redraw());matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{paused=manualPaused||e.matches;IOEngine.redraw()});requestAnimationFrame(tick);
})();
