window.IOTokens={"name": "Impossible Outcomes", "source": "Black and White anchor full-strength Solar Ember and Blue Sky; Navy, Sky Pale, and Ember Soft connect colors inside fields.", "colors": {"black": "#000000", "navy": "#0D1C43", "blue": "#2C9FF4", "blueSoft": "#3D6DF4", "bluePale": "#A3C1DC", "terracotta": "#ED876B", "orange": "#F46138", "white": "#FFFFFF"}, "type": {"display": {"family": "Poppins", "weight": 900, "tracking": "-0.04em", "leading": 0.92}, "voice": {"family": "Poppins", "weight": 300, "tracking": "-0.015em"}, "body": {"family": "Proxima Nova", "weight": 400, "size": 17}, "label": {"family": "Proxima Nova", "weight": 700, "tracking": "0.17em", "size": 11}, "heading": {"family": "Poppins", "weight": 500}, "emphasis": {"family": "Proxima Nova", "weight": 700}}, "motion": {"fieldRates": [0.02, -0.017], "introDuration": 1.1, "lineDelay": 0.11, "lensFollow": 0.13, "fieldFollow": 0.02, "grainFps": 12, "reducedMotion": "static field, immediate text, no cursor following"}, "field": {"zoom": 0.72, "spacing": 4.27, "size": 0.82, "spread": 2.4, "displace": 2.4, "seed": 0.3197, "defaultPreset": "site"}, "extensions": {"grid": "12 columns, 4 on small screens", "materialModes": ["field", "fold", "ribbon", "eclipse", "orb", "chrome", "thermal", "screen", "lines", "edge", "diffusion", "ink-type", "line-screen-type", "diagram"], "applicationColors": "Canonical stops only; interpolated colors are part of field rendering, not extra swatches."}, "colorNames": {"black": "Black", "navy": "Navy", "blue": "Blue Sky", "blueSoft": "Blue Violet", "bluePale": "Sky Pale", "terracotta": "Ember Soft", "orange": "Solar Ember", "white": "White"}, "colorDerivation": {"navy": "Blue Violet hue at OKLab L 0.24, C 0.077", "bluePale": "Blue Sky hue at OKLab L 0.80, C 0.05", "terracotta": "Solar Ember hue at OKLab L 0.73, C 0.13"}, "roles": {"ink": "black", "surface": "white", "depth": "black", "displayBlue": "blue", "accent": "orange", "markInk": "black", "reading": "black"}, "forbiddenColors": ["#076FE0", "#FE5B19"], "performance": {"contexts": 1, "maxDpr": 1.5, "maxDimension": 1800, "maxPixels": 2400000, "maxVisibleCanvases": 6, "fieldFps": 15, "maxGrain": 0.24, "offscreen": "paused", "hiddenDocument": "paused"}, "accessibility": {"normalTextMinimum": 4.5, "largeTextMinimum": 3, "readingInk": "black", "blueVioletOnWhite": 4.475506485434, "blueSkyOnWhite": 2.848353618728, "note": "Keep exact colors. Blue Violet/White is below 4.5:1; Blue Sky/White is below 3:1. Use Black for reading text on White. Blue Violet is suitable for large type on White; marks and fields have separate roles."}};
(() => {
'use strict';
const aliases={blueSoft:'blue-soft',bluePale:'blue-pale'};
const luminance=h=>{const c=[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722};
const contrast=(a,b)=>{const x=luminance(a),y=luminance(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
const css=':root{'+Object.entries(IOTokens.colors).map(([k,v])=>'--'+(aliases[k]||k)+':'+v).join(';')+';'+Object.entries(IOTokens.roles).map(([k,v])=>'--'+k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())+':var(--'+(aliases[v]||v)+')').join(';')+'}';
const style=document.createElement('style');style.id='io-token-properties';style.textContent=css;document.head.append(style);
window.IOColor={luminance,contrast,css,keys:Object.keys(IOTokens.colors),get:key=>IOTokens.colors[key]};
function freeze(obj){Object.values(obj).forEach(v=>{if(v&&typeof v==='object')freeze(v)});return Object.freeze(obj)}freeze(IOTokens);
})();
