(()=>{'use strict';
const $=s=>document.querySelector(s),apps=IOApplications;let current=apps[0],activeScene,saveTimer;
const key='codex-impossible-toolkit-v1';let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
function toast(s){$('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.role='status';el.textContent=s;document.body.append(el);setTimeout(()=>el.remove(),3000)}
function download(name,data,type='text/plain'){const a=document.createElement('a');a.download=name;a.href=URL.createObjectURL(new Blob([data],{type}));a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function fitType(root){root.querySelectorAll('svg [data-svg-edit]').forEach(e=>{e.style.removeProperty('font-size');const width=e.ownerSVGElement.viewBox.baseVal.width-2*Number(e.getAttribute('x')),length=e.getComputedTextLength();if(length>width)e.style.fontSize=(parseFloat(getComputedStyle(e).fontSize)*width/length)+'px'});root.querySelectorAll('.display[contenteditable]').forEach(e=>{e.style.removeProperty('font-size');const f=parseFloat(getComputedStyle(e).fontSize);if(e.scrollWidth>e.clientWidth+1)e.style.fontSize=(f*e.clientWidth/e.scrollWidth*.98)+'px'})}
function scale(wrap){const app=apps.find(a=>a.id===wrap.dataset.app),holder=wrap.parentElement;if(!app)return;let s;if(holder.classList.contains('thumb'))s=Math.min(holder.clientWidth*.90/app.w,holder.clientHeight*.86/app.h);else{const pad=parseFloat(getComputedStyle(holder).paddingLeft)*2;s=Math.min((holder.clientWidth-pad)/app.w,(innerWidth<600?520:730)/app.h)}s=Math.max(.05,s);wrap.style.width=app.w*s+'px';wrap.style.height=app.h*s+'px';wrap.firstElementChild.style.transform=`scale(${s})`;fitType(wrap.firstElementChild)}
function scene(app,thumb=false){const wrap=document.createElement('div');wrap.className='scene-wrap';wrap.dataset.app=app.id;const d=document.createElement('div');d.className='scene '+app.class;d.style.cssText=`width:${app.w}px;height:${app.h}px;${app.color?'color:'+app.color:''}`;d.innerHTML=(!thumb&&saved[app.id]?.html)||app.body;if(!thumb&&saved[app.id]?.scale)d.style.setProperty('--titleScale',saved[app.id].scale);if(thumb){d.querySelectorAll('[contenteditable]').forEach(n=>n.removeAttribute('contenteditable'));d.setAttribute('aria-hidden','true')}wrap.append(d);return wrap}
function save(notify=false){if(!activeScene)return;saved[current.id]={html:activeScene.innerHTML,scale:activeScene.style.getPropertyValue('--titleScale')||1};try{localStorage.setItem(key,JSON.stringify(saved));if(notify)toast('Edits saved on this device.')}catch{toast('Local storage is full. Export HTML to keep your edits.')}}
function geometryControls(){
 let panel=document.getElementById('app-geometry');
 if(!panel){panel=document.createElement('details');panel.id='app-geometry';panel.className='geometry-controls';document.querySelector('.app-inspector').after(panel)}
 const c=activeScene.querySelector('canvas');panel.hidden=!c;if(!c)return;
 const mode=c.dataset.material||'field',caps=IOEngine.capabilities[mode]||[],defaults=IOEngine.defaults[mode]||IOEngine.presets[c.dataset.preset||'site'];
 const ranges={seed:[0,1,.001,'Arrangement'],scale:[1,28,.1,'Density'],rotation:[-3.14,3.14,.01,'Angle'],offset:[-1,1,.01,'Position'],displace:[0,6,.05,'Bend'],size:[.15,1,.01,'Blend']};
 panel.replaceChildren();const summary=document.createElement('summary');summary.textContent='Material geometry';panel.append(summary);const group=document.createElement('div');panel.append(group);
 for(const k of caps){const [min,max,step,label]=ranges[k],row=document.createElement('label'),input=document.createElement('input'),out=document.createElement('output');input.type='range';input.min=min;input.max=max;input.step=step;input.value=c.dataset[k]??defaults[k]??.3197;input.setAttribute('aria-label',label);out.value=Number(input.value).toFixed(2);row.append(label,input,out);group.append(row);input.oninput=()=>{out.value=Number(input.value).toFixed(2);activeScene.querySelectorAll('canvas').forEach(cv=>{const allowed=IOEngine.capabilities[cv.dataset.material||'field']||[];if(allowed.includes(k)){cv.dataset[k]=input.value;IOEngine.draw(cv,IOEngine.time)}});save()}}
}
function select(id){save();current=apps.find(a=>a.id===id)||apps[0];const holder=$('#app-stage');holder.replaceChildren(scene(current));activeScene=holder.querySelector('.scene');$('#app-title').textContent=current.name;$('#app-format').textContent=current.format;$('#app-rule').textContent=current.rule;$('#app-register').textContent=current.register+' / '+String(apps.indexOf(current)+1).padStart(2,'0');$('#app-scale').value=saved[current.id]?.scale||1;$('#app-preset').value=activeScene.querySelector('canvas')?.dataset.preset||current.preset||'prism';$('#app-preset').disabled=!activeScene.querySelector('canvas');$('#app-grain').disabled=!activeScene.querySelector('canvas');$('#app-grain').value=activeScene.querySelector('canvas')?.dataset.grain||.1;$('#svg-edit-label').hidden=current.id!=='hello';$('#svg-text').value=activeScene.querySelector('[data-svg-edit]')?.textContent||'Hello.';
 activeScene.addEventListener('input',()=>{fitType(activeScene);clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(),250)});activeScene.querySelectorAll('svg text:not(:has(tspan)),svg tspan').forEach(n=>n.addEventListener('dblclick',()=>{if(current.id==='hello'&&n===activeScene.querySelector('[data-svg-edit]'))$('#svg-text').focus();else{const v=prompt('Edit text',n.textContent);if(v!==null){n.textContent=v;save()}}}));scale(holder.firstChild);IOEngine.scan(holder);geometryControls();document.querySelectorAll('.template-card').forEach(b=>b.classList.toggle('active',b.dataset.id===id));if(current.id==='diagram')$('#app-construction').textContent='Native SVG nodes, paths, and type. Export to edit coordinates or labels in the standalone file.';else $('#app-construction').textContent='Live text and vector marks over an independently rendered material. Layout dimensions remain explicit in the exported file.';
}
function gallery(category='all'){const groups={campaign:['campaign','resolve','series','ooh','typeposter','hello'],social:['story','feed','carousel','profile'],deck:['deck','divider','capabilities'],document:['cover','spread','brief','report','diagram'],other:['web','app','stationery','film']};const rows=category==='all'?apps:apps.filter(a=>groups[category].includes(a.id));const grid=$('#template-grid');grid.replaceChildren();for(const a of rows){const b=document.createElement('button');b.className='template-card';b.dataset.id=a.id;b.innerHTML=`<div class="thumb"></div><span class="name">${a.name}</span><span class="format">${a.format}</span>`;b.querySelector('.thumb').append(scene(a,true));b.onclick=()=>{select(a.id);$('#app-stage').scrollIntoView({block:'center',behavior:'smooth'})};grid.append(b);scale(b.querySelector('.scene-wrap'))}IOEngine.scan(grid)}
function standalone(app,body){const A=IOBundle;return `<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Impossible — ${app.name}</title><style>${A.fontCSS}\n${A.brandCSS}\n${A.css}</style></head><body class="export-page">${IODefs}<div class="scene-wrap" id="export-wrap"><div class="scene ${app.class}" id="export-scene" style="width:${app.w}px;height:${app.h}px;${app.color?'color:'+app.color+';':''}--titleScale:${activeScene?.style.getPropertyValue('--titleScale')||1}">${body}</div></div><div class="export-tools"><button id="save-html">Save edited HTML ↓</button><button id="toggle-motion">Pause / play</button></div><script>${A.tokenRuntime}<\/script><style>${A.brandCSS}</style><script>${A.fieldSource}<\/script><script>${A.materialSource}<\/script><script>${A.engine}<\/script><script>
 const w=document.getElementById('export-wrap'),s=document.getElementById('export-scene');${fitType.toString()}
 function fit(){const k=Math.min((innerWidth-32)/${app.w},(innerHeight-80)/${app.h});w.style.width=${app.w}*k+'px';w.style.height=${app.h}*k+'px';s.style.transform='scale('+k+')';fitType(s);IOEngine.redraw()}fit();document.fonts.ready.then(fit);s.addEventListener('input',()=>fitType(s));addEventListener('resize',fit);IOEngine.scan();document.getElementById('toggle-motion').onclick=()=>IOEngine.setPaused(!IOEngine.paused);document.getElementById('save-html').onclick=()=>{const a=document.createElement('a');a.download='Impossible-${app.id}-edited.html';a.href=URL.createObjectURL(new Blob(['<!doctype html>'+document.documentElement.outerHTML],{type:'text/html'}));a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};document.querySelectorAll('svg text:not(:has(tspan)),svg tspan').forEach(t=>t.addEventListener('dblclick',()=>{let v=prompt('Edit text',t.textContent);if(v!==null){t.textContent=v;fitType(s)}}));
 <\/script></body></html>`}
window.Toolkit={select,standalone,apps,get current(){return current},get scene(){return activeScene}};
$('body').insertAdjacentHTML('beforeend',IODefs);
const colors=Object.entries(IOTokens.colors).map(([k,h])=>[IOTokens.colorNames[k],h]);
$('#colors').innerHTML=colors.map(([n,h],i)=>`<div class="swatch" style="background:${h};color:${IOColor.contrast(h,IOTokens.colors.black)>=4.5?IOTokens.colors.black:IOColor.contrast(h,IOTokens.colors.white)>=4.5?IOTokens.colors.white:IOTokens.colors.black};${i===7?'border:1px solid #ddd':''}"><span>${n}</span><code>${h}</code></div>`).join('');
function lum(hex){const c=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722}function ratio(a,b){const x=lum(a),y=lum(b);return((Math.max(x,y)+.05)/(Math.min(x,y)+.05)).toFixed(2)}
$('#contrast-orange').textContent='Ember / Black · '+ratio(IOTokens.colors.orange,IOTokens.colors.black)+':1';$('#contrast-blue').textContent='White / Violet · '+ratio(IOTokens.colors.white,IOTokens.colors.blueSoft)+':1';$('#contrast-navy').textContent='Black / White · '+ratio(IOTokens.colors.black,IOTokens.colors.white)+':1';
const materials=[
{id:'fold',n:'01',name:'Folded field',read:'A pressed surface. Ember faces, navy valleys, one raking light.',chain:{source:'warped diagonal ramp (site field phase)',structure:'a slow rise across 72% of each period and a steep rounded return; both segments are smoothstep pieces, so the height is C1 across the crest and the wrap',response:'matte: key light from the upper left shades the faces from deep red to full Ember; a cool back light from the lower right lifts the return faces from Navy through Violet to a Sky-lit crest',formation:'troughs close through Navy into Black; no specular',screen:'fine single-pixel grain in lightness, gated to the lit faces',temporal:'phase drifts at the site rates; ridges never spin',composition:'type sits on a broad face, never across a valley'},use:'Covers · full-bleed dividers',attrs:'data-grain=".07"',feature:true},
{id:'ribbon',n:'02',name:'Grain ribbon',read:'Two bands of one surface, twisting through the whole ramp.',chain:{source:'curve c(x) + width w(x), both fbm-modulated',structure:'signed distance across the band; two layers',response:'density = √(1−a²) drives lightness and grain',formation:'flat view, back band darker',screen:'heavy grain, gated to density',temporal:'slow twist; width breathes',composition:'reserve the dark field for type'},use:'Posters · key visuals',attrs:'data-grain=".08"',wide:true},
{id:'eclipse',n:'03',name:'Eclipse',read:'A dark reserve with one luminous edge and a directional corona.',chain:{source:'radial distance from a disk',structure:'exp falloff + angular fbm rays, biased to one direction',response:'Sky on the lower limb, Ember on the upper limb; white only at the flare',formation:'black center preserved; rim at 1px',screen:'flare point on the bright limb',temporal:'rays drift; the disk never moves',composition:'the disk is the counter-form for a statement'},use:'Focus slides · social',attrs:'data-grain=".06"'},
{id:'orb',n:'04',name:'Orbs',read:'Six flat disks, each a shaped gradient of one color.',chain:{source:'six placed disks; the seed jitters position and light angle',structure:'anti-aliased disks painted back to front; one light direction across each disk',response:'no sphere shading: the token at the lit edge falls through its own dark relative (Ember → deep red, Sky → Violet, Violet → Navy) with a soft bloom of the lighter relative inside the lit edge',formation:'flat; lightness falls with the light and the hue holds',screen:'fbm mottle in the coverage; fine grain gated to the lit side',temporal:'static; seed changes the arrangement',composition:'one large Sky mass low left, Ember and Violet bodies around it; reserve upper right'},use:'Concept systems · OOH',attrs:'data-grain=".08"'},
{id:'chrome',n:'05',name:'Prism',read:'A long exposure of light through a prism: parallel bands along one diagonal, brightening to white where they overlap.',chain:{source:'one diagonal axis; distance across it',structure:'seven parallel gaussian bands at a fixed pitch: Navy, Violet, Sky, Pale-to-White, Ember, Ember Soft, Navy',response:'the bands add in linear light on black and roll off with a soft tone curve; exposure varies along the streak and steps faintly',formation:'flat; the streak enters and leaves through the void',screen:'film grain in the light',temporal:'exposure drifts along the streak',composition:'the streak crosses once, upper left to lower right; type in the dark'},use:'Hero frames · titles',attrs:'data-grain=".10"'},
{id:'thermal',n:'06',name:'Thermal body',read:'A warm body on paper, read through its edge.',chain:{source:'three drifting metaballs: one mass, two satellites',structure:'m−1 field with a fine fbm edge',response:'Ember body lifting toward Ember Soft at the center; the edge runs Navy hairline → Violet → Sky → Sky Pale → paper',formation:'flat; the edge is the image',screen:'grain lives in the halo, like a thermal print',temporal:'bodies drift and merge',composition:'paper is the material; the mass sits off center'},use:'Light layouts · print',attrs:'data-grain=".08"',paper:true},
{id:'screen',n:'07',name:'Burst',read:'Rays of light converging on a black axis. A cross through the center stays void.',chain:{source:'polar coordinates about one point',structure:'angular fbm makes the rays; a soft cross of black through the center',response:'Ember through White to Sky by angle, adding in linear light; a soft tone curve',formation:'the axis is the counter-form; the rays run to the frame',screen:'film grain in the light',temporal:'static; seed turns the rays',composition:'the mark or a word sits on the axis'},use:'Focus frames · social',attrs:'data-grain=".10"'},
{id:'lines',n:'08',name:'Line screen',read:'One ink, one fine pitch. A body appears only as line weight.',chain:{source:'one soft body, modulated by the site field phase',structure:'a fine near-horizontal pitch that bows slightly over the body',response:'near solid at the center of the body, hairline at its edge, gone in the reserve above',formation:'paper white',screen:'none beyond the screen itself',temporal:'static',composition:'the body sits low; the upper third is reserve'},use:'Editorial · reports',attrs:'data-grain=".03"',paper:true},
{id:'edge',n:'09',name:'Edge light',read:'One luminous line. Everything else is reserve.',chain:{source:'curve across the frame',structure:'a one-pixel core; asymmetric glow (Ember below, Sky above); displaced hairs of Violet, Sky, Ember Soft and Ember at 2 and 5 px',response:'emission adds in linear light, so the glow keeps the token hues; a soft tone curve holds it in range',formation:'brightness travels along the line',screen:'the grain lives in the glow',temporal:'the line breathes',composition:'type above or below, never on the line'},use:'Title frames · dividers',attrs:'data-grain=".06"'}];
const typeMaterials=[
{n:'10',name:'Type diffusion',read:'One statement. Sharp Ember at the source, dissolving into Sky along the word.',html:'<div class="type-diffusion"><b contenteditable="plaintext-only" spellcheck="false" data-sync="diffusion">Make it\nreal.</b><b aria-hidden="true">Make it\nreal.</b><b aria-hidden="true">Make it\nreal.</b><b aria-hidden="true">Make it\nreal.</b></div>',use:'Motion titles · social',chain:{source:'live text, one string',structure:'four copies of the same text, masked along one diagonal',screen:'blur 0 → .3 → 1.2 → 4.5 cqw; color Ember → Violet → Sky',composition:'anchored lower left; the diffusion leaves through the upper right'}},
];
const fieldMaterials=[
{id:'field',n:'11',name:'Primary field',read:'The hero ramp itself: black, navy, sky, ember, black — color interpolated in light, opening and closing on the void.',chain:{source:'a rotated linear axis plus a slow, wide fbm warp',structure:'five stops, five equal segments; handover width 0.75',response:'OKLab interpolation, no hue shoulder; the ember reads as a flare against black',formation:'black covers close to half the frame',screen:'film grain 0.14 at 12fps',temporal:'rates +0.020 and −0.017; the field never spins',composition:'reserve the black for type'},use:'Covers · hero · everything',attrs:'data-preset="site" data-grain=".14"'},
{id:'field',n:'12',name:'Applied',read:'The mark over the primary field: one asset, one field, the whole identity.',chain:{source:'the primary field',structure:'the exact mark as a mask, centered',response:'white ink; the field passes behind it untouched',formation:'the mark holds the center; the field carries the frame',screen:'as the field',temporal:'as the field',composition:'nothing else in the frame'},use:'Social · stamps · signatures',attrs:'data-preset="site" data-grain=".14" data-offset=".2"',applied:true}];
const computedCard=m=>`<article class="material-card${m.wide?' wide':''}${m.paper?' paper':''}${m.applied?' applied':''}" data-id="${m.id}" data-n="${m.n}"><div class="art"><canvas class="material" data-material="${m.id}" ${m.attrs||''} aria-label="${m.name}"></canvas><span class="idx label">${m.n}</span>${IOMark}</div><div class="meta"><h3>${m.name}</h3><span class="use">${m.use}</span><p class="read">${m.read}</p></div></article>`;
const typeCard=m=>`<article class="material-card${m.paper?' paper':''}" data-n="${m.n}"><div class="art">${m.html}<span class="idx label" ${m.paper?'style="color:#000"':''}>${m.n}</span></div><div class="meta"><h3>${m.name}</h3><span class="use">${m.use}</span><p class="read">${m.read}</p></div></article>`;
$('#material-grid').innerHTML=[...materials.filter(m=>!m.feature).map(m=>[m.n,computedCard(m)]),...typeMaterials.map(m=>[m.n,typeCard(m)]),...fieldMaterials.map(m=>[m.n,computedCard(m)])].sort((a,b)=>a[0].localeCompare(b[0])).map(x=>x[1]).join('');
document.querySelectorAll('#material-grid [data-sync]').forEach(src=>{const copies=[...src.parentElement.querySelectorAll('[aria-hidden]')];src.addEventListener('input',()=>copies.forEach(c=>{c.textContent=src.textContent}))});
$('#material-spec').onclick=e=>{e.preventDefault();download('Impossible-materials.json',JSON.stringify({system:'Impossible Outcomes material system',tokens:IOTokens.colors,colorSpace:'Oklab mixing, sRGB output',colorRule:'the hero ramp — black, navy, sky, ember, black — five equal segments interpolated in OKLab, opening and closing on the void; no hue shoulder. Light materials (prism, burst, edge light) add in linear light.',sharedCause:'phase(uv) — the site field\u2019s fbm-warped diagonal ramp; every computed material derives from it or from one explicit geometric source',grainRule:'single-pixel grain from an integer-quality hash is added to Oklab lightness, scaled per material and gated to the body mask',materials:[...materials,...fieldMaterials].map(m=>({id:m.id,name:m.name,read:m.read,chain:m.chain,use:m.use,defaults:IOEngine.defaults[m.id]||IOEngine.presets.site,dataAttributes:['data-material','data-preset','data-grain',...(IOEngine.capabilities[m.id]||[]).map(k=>'data-'+k)]})),typographic:typeMaterials.map(m=>({name:m.name,read:m.read,chain:m.chain,use:m.use})),shader:'source/materials.frag'},null,2),'application/json')};
$('.menu-toggle').onclick=()=>{let open=$('#navigation').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',open)};$('#navigation').addEventListener('click',e=>{if(e.target.tagName==='A'){$('#navigation').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')}});
function paused(){const b=$('#pause');b.textContent=IOEngine.paused?'Play motion':'Pause motion';b.setAttribute('aria-pressed',IOEngine.paused)}matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>setTimeout(paused,0));$('#pause').onclick=()=>{IOEngine.setPaused(!IOEngine.paused);paused()};paused();
$('#field-preset').onchange=e=>{const c=$('#field-demo');c.dataset.preset=e.target.value;delete c.dataset.size;$('#field-width').value=IOEngine.presets[e.target.value].size;$('#field-width-value').value=$('#field-width').value;IOEngine.draw(c,IOEngine.time)};
$('#field-width').oninput=e=>{$('#field-demo').dataset.size=e.target.value;$('#field-width-value').value=e.target.value;IOEngine.draw($('#field-demo'),IOEngine.time)};$('#field-grain').oninput=e=>{$('#field-demo').dataset.grain=e.target.value;IOEngine.draw($('#field-demo'),IOEngine.time)};
$('#field-reset').onclick=()=>{$('#field-preset').value='site';$('#field-preset').dispatchEvent(new Event('change'));$('#field-grain').value=.14;$('#field-grain').dispatchEvent(new Event('input'))};$('#save-preset').onclick=()=>download('Impossible-field-preset.json',JSON.stringify({preset:$('#field-preset').value,...IOEngine.presets[$('#field-preset').value],size:+$('#field-width').value,grain:+$('#field-grain').value,time:IOEngine.time},null,2),'application/json');
$('#categories').onclick=e=>{const b=e.target.closest('button');if(!b)return;$('#categories').querySelectorAll('button').forEach(n=>n.classList.toggle('active',n===b));gallery(b.dataset.category)};
$('#app-scale').oninput=e=>{activeScene.style.setProperty('--titleScale',e.target.value);fitType(activeScene);save()};$('#app-preset').onchange=e=>{activeScene.querySelectorAll('canvas').forEach(c=>{c.dataset.preset=e.target.value;IOEngine.draw(c,IOEngine.time)});save()};$('#app-grain').oninput=e=>{activeScene.querySelectorAll('canvas').forEach(c=>{c.dataset.grain=e.target.value;IOEngine.draw(c,IOEngine.time)});save()};$('#svg-text').oninput=e=>{activeScene.querySelector('[data-svg-edit]').textContent=e.target.value;fitType(activeScene);save()};$('#app-save').onclick=()=>save(true);$('#app-reset').onclick=()=>{delete saved[current.id];activeScene=null;select(current.id);save();toast('Original composition restored.')};$('#app-export').onclick=()=>{save();download('Impossible-'+current.id+'.html',standalone(current,activeScene.innerHTML),'text/html')};
$('[data-asset]')&&document.querySelectorAll('[data-asset]').forEach(a=>{const name=a.dataset.asset;a.href=IOBundle.files[name]||name});
$('#brief-form').onsubmit=e=>{e.preventDefault();const text=`# Impossible Outcomes — build brief\n\nFormat: ${$('#brief-format').value}\nRegister: ${$('#brief-register').value}\nPrimary material: ${$('#brief-material').value}\n\n## Purpose and content\n${$('#brief-purpose').value}\n\n## Brand rules\n${IOBundle.rules}\n\n## Deliver\nAn editable local HTML artifact, its source assets, and browser QA evidence. Use the enclosed toolkit and canonical asset files. Keep text live, and render the actual final composition before delivery.\n`;download('Impossible-build-brief.md',text,'text/markdown');toast('Build brief downloaded.')};
document.querySelector('.original-studies')?.addEventListener('toggle',()=>{document.querySelectorAll('.scene-wrap').forEach(scale);IOEngine.redraw()});
select(apps[0].id);gallery();IOEngine.scan();document.fonts.ready.then(()=>document.querySelectorAll('.scene-wrap').forEach(scale));addEventListener('resize',()=>document.querySelectorAll('.scene-wrap').forEach(scale));addEventListener('beforeunload',()=>save());
})();
