(()=>{'use strict';
const components=[
 {id:'material',name:'Material window',kind:'Visual',description:'An independent field or surface.',defaults:{title:'Material / folded field'}},
 {id:'text',name:'Editorial text',kind:'Content',description:'A heading, a premise, and supporting detail.',defaults:{title:'Create the conditions.',text:'We don’t create ideas. We create conditions for outcomes.'}},
 {id:'columns',name:'Comparison columns',kind:'Content',description:'Parallel ideas on a shared baseline.',defaults:{title:'Working principles',items:[['Passion','Do what you want and you’ll find you’ve done what you must.'],['Resolve','Don’t compromise.'],['Adaptability','There are many ways to be right and one way to be wrong.']]}},
 {id:'process',name:'Process flow',kind:'Diagram',description:'Four stages with a visible direction.',defaults:{title:'From substance to output.',items:[['Input','Gather the source.'],['Frame','Define the decision.'],['Compose','Build the artifact.'],['Review','Check it in context.']]}},
 {id:'network',name:'System map',kind:'Diagram',description:'One central system and four connected roles.',defaults:{title:'A connected practice.',center:'Outcome',items:[['Strategy','Set the direction.'],['Systems','Connect the parts.'],['Design','Make it clear.'],['Intelligence','Make it useful.']]}},
 {id:'bars',name:'Horizontal bars',kind:'Data',description:'Labels, values, a common scale, and a source.',defaults:{title:'Inventory',items:[],source:''}},
 {id:'ring',name:'Part-to-whole chart',kind:'Data',description:'A total, named segments, and a matching legend.',defaults:{title:'Inventory',items:[],source:''}},
 {id:'matrix',name:'Decision matrix',kind:'Diagram',description:'Comparable options with explicit criteria.',defaults:{title:'Choose the right register.',items:[['Showcase','One idea','Large statement','Material-led'],['Working document','Evidence + detail','Reading hierarchy','Paper-led'],['Presentation','A sequence','One point per frame','Mixed']],headers:['Format','Content','Type','Composition']}},
 {id:'timeline',name:'Sequence / roadmap',kind:'Diagram',description:'An ordered plan without invented dates.',defaults:{title:'Make the next step clear.',items:[['Define','Purpose, audience, and constraints.'],['Build','A working composition with real content.'],['Test','Readability, behavior, and export.'],['Deliver','Editable files and a clear handoff.']]}},
 {id:'callout',name:'Statement / callout',kind:'Content',description:'A short point with an independent color surface.',defaults:{title:'The content sets the structure.',text:'Use the material to support the argument.'}},
 {id:'ledger',name:'Content ledger',kind:'Content',description:'Labeled rows for briefs, specifications, and decisions.',defaults:{title:'Brand elements',items:[['Practice','Strategy. Systems. Design. Intelligence.'],['Type','Poppins and Proxima Nova.'],['Color','Solar Ember and Blue Sky.'],['Mark','Exact SVG artwork.']]}}
];
const templates=[
 {id:'opening',name:'Opening statement',category:'Presentation',format:'wide',layout:'split',material:'chrome',surface:'black',density:'sparse',frame:'none',title:'Create the\nconditions.',intro:'Strategy. Systems. Design. Intelligence.',blocks:{sparse:['material'],standard:['material','text'],detailed:['material','columns']}},
 {id:'social',name:'Social / square',category:'Social',format:'square',layout:'poster',material:'fold',surface:'white',density:'sparse',frame:'social',title:'Make it\nreal.',intro:'The Impossible Outcomes Co.',blocks:{sparse:['material'],standard:['material','text'],detailed:['material','columns']}},
 {id:'story',name:'Social / story',category:'Social',format:'story',layout:'poster',material:'ribbon',surface:'black',density:'sparse',frame:'iphone',title:'Create the\nconditions.',intro:'Then make it real.',blocks:{sparse:['material'],standard:['material','callout'],detailed:['material','ledger']}},
 {id:'brief',name:'Working brief',category:'Documents',format:'letter',layout:'document',material:'edge',surface:'white',density:'detailed',frame:'none',title:'Create the\nconditions.',intro:'Strategy. Systems. Design. Intelligence.',blocks:{sparse:['callout','ledger'],standard:['text','ledger','process'],detailed:['text','ledger','columns','process']}},
 {id:'editorial',name:'Editorial / spread',category:'Documents',format:'wide',layout:'editorial',material:'thermal',surface:'white',density:'standard',frame:'none',title:'Keep the signal. Change the form.',intro:'The material can vary. The brand anchors stay fixed.',blocks:{sparse:['material','text'],standard:['material','text','columns'],detailed:['material','text','columns','ledger']}},
 {id:'overview',name:'Project overview',category:'Presentation',format:'wide',layout:'grid',material:'fold',surface:'white',density:'detailed',frame:'browser',title:'From strategy to the thing itself.',intro:'A shared view of the work, the system, and what happens next.',blocks:{sparse:['columns'],standard:['columns','process'],detailed:['columns','process','ledger','callout']}},
 {id:'process',name:'Process / four stages',category:'Diagrams',format:'wide',layout:'diagram',material:'edge',surface:'white',density:'standard',frame:'none',title:'Give the work a clear direction.',intro:'Input → frame → compose → review.',blocks:{sparse:['process'],standard:['process','text'],detailed:['process','text','ledger']}},
 {id:'system',name:'System / relationships',category:'Diagrams',format:'wide',layout:'diagram',material:'orb',surface:'white',density:'standard',frame:'none',title:'The parts work together.',intro:'Make each role clear. Keep the connections visible.',blocks:{sparse:['network'],standard:['network','text'],detailed:['network','ledger','callout']}},
 {id:'inventory',name:'Infographic / inventory',category:'Information',format:'wide',layout:'grid',material:'screen',surface:'white',density:'standard',frame:'none',title:'Inventory',intro:'',blocks:{sparse:['ring'],standard:['bars','ring'],detailed:['bars','ring','ledger']}},
 {id:'comparison',name:'Comparison / matrix',category:'Information',format:'wide',layout:'diagram',material:'lines',surface:'white',density:'standard',frame:'none',title:'Match the format to the work.',intro:'Choose the content structure before choosing the surface.',blocks:{sparse:['matrix'],standard:['matrix','callout'],detailed:['matrix','columns','text']}},
 {id:'roadmap',name:'Roadmap / sequence',category:'Diagrams',format:'wide',layout:'diagram',material:'edge',surface:'white',density:'standard',frame:'none',title:'Make the next move clear.',intro:'An ordered plan with space for decisions and ownership.',blocks:{sparse:['timeline'],standard:['timeline','ledger'],detailed:['timeline','ledger','columns']}},
 {id:'outputs',name:'Infographic / outputs',category:'Information',format:'portrait',layout:'document',material:'fold',surface:'white',density:'standard',frame:'none',title:'One brief.\nThree outputs.',intro:'Keep the content connected as the format changes.',blocks:{sparse:['columns','material'],standard:['columns','process','material'],detailed:['text','columns','process','ledger']}}
];
const formats={wide:{name:'Landscape · 16:9',w:1600,h:900},square:{name:'Square · 1:1',w:1080,h:1080},story:{name:'Story · 9:16',w:1080,h:1920},letter:{name:'Document · US Letter',w:850,h:1100},portrait:{name:'Portrait · 4:5',w:1080,h:1350}};
window.IOStudioRegistry={version:1,components,templates,formats};
})();
