(()=>{'use strict';
const R=IOStudioRegistry,$=s=>document.querySelector(s),clone=x=>JSON.parse(JSON.stringify(x)),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='codex-impossible-application-studio-v1',materials=['field','fold','ribbon','eclipse','orb','chrome','thermal','screen','lines','edge'];let view='templates',inspector='layout',category='All',libraryDensity='template',guides=false,zoom=false,materialTarget='all',saveTimer;
const mark='<span class="brand-mark" data-locked="true" aria-label="Impossible Outcomes mark"></span>';
function block(id){const c=R.components.find(c=>c.id===id);return{type:id,...clone(c.defaults)}}
function create(id,density){const t=R.templates.find(t=>t.id===id)||R.templates[0],d=density||t.density;return{version:1,template:t.id,name:t.name,format:t.format,layout:t.layout,frame:t.frame,surface:t.surface,density:d,title:t.title,intro:t.intro,kicker:'THE IMPOSSIBLE OUTCOMES CO.',footer:'STRATEGY / SYSTEMS / DESIGN / INTELLIGENCE',material:t.material,palette:'prism',grain:.055,seed:.3197,rotation:IOEngine.defaults[t.material]?.rotation||-.55,scale:IOEngine.defaults[t.material]?.scale||3,offset:IOEngine.defaults[t.material]?.offset??.1,size:.78,displace:IOEngine.defaults[t.material]?.displace??2.4,blocks:t.blocks[d].map(block)}}
function validate(p){if(!p||p.version!==1||!R.templates.some(t=>t.id===p.template)||!R.formats[p.format]||!['sparse','standard','detailed'].includes(p.density)||!Array.isArray(p.blocks)||p.blocks.length>6)throw Error('Choose an Application Studio project file.');const out=create(p.template,p.density);for(const k of ['title','intro','kicker','footer','name'])if(typeof p[k]==='string')out[k]=p[k].slice(0,12000);for(const [k,valid] of Object.entries({layout:['split','poster','document','editorial','grid','diagram'],frame:['none','iphone','social','browser'],surface:['white','black','ember'],material:materials,palette:['prism','site','blue','orange']}))if(valid.includes(p[k]))out[k]=p[k];out.format=p.format;for(const[k,lo,hi]of[['grain',0,.24],['seed',0,1],['rotation',-3.14,3.14],['scale',1,28],['offset',-1,1],['size',.25,1.2],['displace',0,6]])if(Number.isFinite(p[k]))out[k]=Math.min(hi,Math.max(lo,p[k]));out.blocks=p.blocks.map(b=>{if(!R.components.some(c=>c.id===b.type))throw Error('Unknown component.');const x=block(b.type);for(const k of ['title','text','center','source'])if(typeof b[k]==='string')x[k]=b[k].slice(0,12000);for(const k of ['items','headers'])if(Array.isArray(b[k]))x[k]=b[k].slice(0,12).map(row=>Array.isArray(row)?row.slice(0,5).map(v=>typeof v==='number'?Math.max(0,Math.min(1e9,v)):String(v).slice(0,2000)):String(row).slice(0,200));if(x.items&&x.items.some(r=>!Array.isArray(r)||r.length<2))throw Error('Each component row needs at least two columns.');if(['bars','ring'].includes(x.type)&&x.items.some(r=>!Number.isFinite(Number(r[1]))||Number(r[1])<0))throw Error('Chart values must be nonnegative numbers.');if(['process','timeline','network'].includes(x.type))x.items=x.items.slice(0,4);if(b.appearance&&typeof b.appearance==='object')x.appearance=materialValues(b.appearance,out);return x});return out}
function materialValues(p,base){const a={};for(const k of ['material','palette','grain','seed','rotation','scale','offset','size','displace'])a[k]=p[k]??base[k];if(!materials.includes(a.material))a.material=base.material;if(!['prism','site','blue','orange'].includes(a.palette))a.palette=base.palette;for(const[k,lo,hi]of[['grain',0,.24],['seed',0,1],['rotation',-3.14,3.14],['scale',1,28],['offset',-1,1],['size',.25,1.2],['displace',0,6]])a[k]=Number.isFinite(a[k])?Math.min(hi,Math.max(lo,a[k])):base[k];return a}
function activeMaterial(){const b=state.blocks[Number(materialTarget)];return materialTarget==='all'||!b?state:(b.appearance??=materialValues(state,state))}
let state=create('opening');try{const s=localStorage.getItem(key);if(s)state=validate(JSON.parse(s))}catch{}
function put(path,value){const p=path.split('.');let o=state;for(const k of p.slice(0,-1))o=o[k];o[p.at(-1)]=value}
function message(s){const el=$('#studio-status');el.textContent=s;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),2600)}
function persist(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{message('Save a project file to keep your changes.')}},150)}
const edit=(text,path,tag='span',cls='',editable=true)=>`<${tag} class="${cls}" data-edit="${path}" ${editable?'contenteditable="plaintext-only" spellcheck="false"':''}>${esc(text)}</${tag}>`;
function component(b,i,s,editable){const p=`blocks.${i}`,E=(t,k,tag='span',c='')=>edit(t,`${p}.${k}`,tag,c,editable),title=E(b.title,'title','h2','component-title');let inner='';
 if(b.type==='material'){const m={...s,...b.appearance};return`<section class="component component-material"><canvas class="material" ${editable?'data-live="true"':''} data-size="${m.size}" data-displace="${m.displace}" data-block-index="${i}" data-material="${m.material}" data-preset="${m.palette}" data-grain="${m.grain}" data-seed="${m.seed}" data-scale="${m.scale}" data-rotation="${m.rotation}" data-offset="${m.offset}" aria-label="${m.material} material"></canvas><div class="material-caption">${esc(m.material)} / ${esc(m.palette==='prism'?'Ember + Sky':m.palette)}</div></section>`;}
 if(b.type==='text'||b.type==='callout')inner=E(b.text,'text','p','component-copy');
 if(b.type==='columns')inner='<div class="comparison-columns">'+b.items.map((r,n)=>`<div class="comparison-column"><span class="number">0${n+1}</span>${E(r[0],`items.${n}.0`,'h3')}${E(r[1],`items.${n}.1`,'p')}</div>`).join('')+'</div>';
 if(b.type==='ledger')inner='<table class="ledger"><tbody>'+b.items.map((r,n)=>`<tr><th>${E(r[0],`items.${n}.0`)}</th><td>${E(r[1],`items.${n}.1`)}</td></tr>`).join('')+'</tbody></table>';
 if(b.type==='matrix')inner='<table class="matrix"><thead><tr>'+b.headers.map((h,n)=>`<th>${E(h,`headers.${n}`)}</th>`).join('')+'</tr></thead><tbody>'+b.items.map((r,n)=>'<tr>'+r.map((c,j)=>`<td>${E(c,`items.${n}.${j}`)}</td>`).join('')+'</tr>').join('')+'</tbody></table>';
 if(b.type==='process')inner='<div class="flow">'+b.items.map((r,n)=>`<div class="flow-node"><div class="number">0${n+1}</div>${E(r[0],`items.${n}.0`,'h3')}${E(r[1],`items.${n}.1`,'p')}</div>`).join('')+'</div>';
 if(b.type==='timeline')inner='<div class="timeline">'+b.items.map((r,n)=>`<div class="timeline-node"><div class="number">STAGE 0${n+1}</div>${E(r[0],`items.${n}.0`,'h3')}${E(r[1],`items.${n}.1`,'p')}</div>`).join('')+'</div>';
 if(b.type==='network'){const positions=[[15,22],[85,22],[15,78],[85,78]];inner='<div class="network"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width=".23"><path d="M25 22C40 22 33 50 40 50M75 22C60 22 67 50 60 50M25 78C40 78 33 50 40 50M75 78C60 78 67 50 60 50"/></g><g fill="var(--orange)"><circle cx="40" cy="50" r=".8"/><circle cx="60" cy="50" r=".8"/></g></svg>'+b.items.slice(0,4).map((r,n)=>`<div class="network-node" style="left:${positions[n][0]}%;top:${positions[n][1]}%">${E(r[0],`items.${n}.0`,'strong')}${E(r[1],`items.${n}.1`,'p')}</div>`).join('')+`<div class="network-node center">${E(b.center,'center')}</div></div>`}
 if(b.type==='bars'){const max=Math.max(1,...b.items.map(r=>Number(r[1])||0));inner='<div class="bars">'+b.items.map((r,n)=>`<div class="bar-row"><span>${esc(r[0])}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(0,Number(r[1])||0)/max*100}%"></div></div><span class="bar-number">${esc(Number(r[1])||0)}</span></div>`).join('')+'</div>'+E(b.source,'source','p','data-source')}
 if(b.type==='ring'){const values=b.items.map(r=>Math.max(0,Number(r[1])||0)),total=values.reduce((a,b)=>a+b,0),colors=['var(--orange)','var(--blue)','var(--blue-soft)','#000','#fff'];let offset=0;const circles=values.map((v,n)=>{const start=offset;offset+=total?v/total*100:0;return`<circle cx="110" cy="110" r="84" fill="none" stroke="${colors[n%5]}" stroke-width="30" pathLength="100" stroke-dasharray="${total?v/total*100:0} 100" stroke-dashoffset="${-start}" transform="rotate(-90 110 110)"/>`}).join('');inner=`<div class="ring-content"><svg class="ring-art" viewBox="0 0 220 220" role="img" aria-label="${esc(b.title)}"><circle cx="110" cy="110" r="99" fill="none" stroke="currentColor" stroke-width="1"/>${circles}<text x="110" y="111" text-anchor="middle" font-size="42" font-weight="900">${total}</text><text x="110" y="138" text-anchor="middle" font-size="12">TOTAL</text></svg><div class="ring-key">${b.items.map((r,n)=>`<div><i style="background:${colors[n%5]}"></i><span>${esc(r[0])}</span><b>${esc(values[n])}</b></div>`).join('')}</div></div>`+E(b.source,'source','p','data-source')}
 return`<section class="component component-${b.type}" data-component="${b.type}">${title}${inner}</section>`;
}
function dimensions(s){const f=R.formats[s.format],u=f.w/100;return{w:f.w+(s.frame==='iphone'?3*u:s.frame==='none'?0:2),h:(s.frame==='iphone'?Math.max(f.h,f.w*19.5/9):f.h)+(s.frame==='iphone'?3*u:s.frame==='browser'?4*u:s.frame==='social'?13*u:0)+(s.frame==='browser'||s.frame==='social'?2:0)}}
function render(s,editable=false,only=false,authoring=false){const f=R.formats[s.format],art=`<article class="art-page layout-${s.layout} density-${s.density} surface-${s.surface} format-${s.format}${only?' component-only':''}${guides&&authoring?' show-guides':''}" style="--art-w:${f.w}px;--art-h:${f.h}px"><header class="art-top">${mark}${edit(s.kicker,'kicker','div','art-kicker',editable)}</header><div class="art-body"><div class="art-titleblock">${edit(s.title,'title','h1','art-title',editable)}${edit(s.intro,'intro','p','art-intro',editable)}</div><div data-count="${s.blocks.length}" class="art-content${s.blocks.length===1?' single':''}">${s.blocks.map((b,i)=>component(b,i,s,editable)).join('')}</div></div><footer class="art-foot">${edit(s.footer,'footer','span','',editable)}<span>IMPOSSIBLE</span></footer></article>`;
 const chrome=s.frame==='browser'?'<div class="browser-chrome"><i></i><i></i><i></i><span>Impossible / Preview</span></div>':s.frame==='social'?`<div class="social-chrome">${mark}<div>Impossible Outcomes<small>Strategy / Systems / Design / Intelligence</small></div><span>•••</span></div>`:'';
 const tail=s.frame==='social'?'<div class="social-actions"><span>♡</span><span>↗</span><span class="social-caption">The Impossible Outcomes Co.</span></div>':'';
 const d=dimensions(s);return`<div class="composition-fit" data-width="${d.w}" data-height="${d.h}"><div class="composition-shell frame-${s.frame}" style="width:${d.w}px;height:${d.h}px;--unit:${f.w/100}px;--frame-ground:${s.surface==='black'?'#000':s.surface==='ember'?'var(--orange)':'#fff'}">${chrome}<div class="frame-screen">${art}</div>${tail}</div></div>`
}
function fit(holder){const wrap=holder.querySelector('.composition-fit');if(!wrap)return;const st=getComputedStyle(holder),width=holder.clientWidth-parseFloat(st.paddingLeft)-parseFloat(st.paddingRight),height=holder.clientHeight-parseFloat(st.paddingTop)-parseFloat(st.paddingBottom),w=Number(wrap.dataset.width),h=Number(wrap.dataset.height),k=holder.id==='studio-stage'&&zoom?1:Math.max(.01,Math.min(width/w,height/h));wrap.style.width=w*k+'px';wrap.style.height=h*k+'px';wrap.firstElementChild.style.transform=`scale(${k})`}
function overflow(){const root=$('#studio-stage');if(!root||view!=='editor')return[];const issues=[...root.querySelectorAll('.component,.art-content')].filter(e=>e.scrollHeight>e.clientHeight+3||e.scrollWidth>e.clientWidth+3);const el=$('#layout-status');el.textContent=issues.length?'Content needs more room. Reduce copy or remove a component.':R.formats[state.format].w+' × '+R.formats[state.format].h+(IOEngine.error?' · Static material fallback':' · Live text');el.classList.toggle('problem',!!issues.length);return issues.map(e=>e.className)}
function draw(){const stage=$('#studio-stage');stage.innerHTML=render(state,true,false,true);fit(stage);IOEngine.scan(stage);$('#composition-name').textContent=state.name;$('#format-readout').textContent=R.formats[state.format].name+' / '+({none:'Artwork',iphone:'iPhone',social:'Social',browser:'Browser'}[state.frame]);stage.querySelectorAll('[data-edit]').forEach(el=>{el.addEventListener('blur',()=>{put(el.dataset.edit,el.innerText);persist();overflow()});el.addEventListener('paste',event=>{event.preventDefault();document.execCommand('insertText',false,event.clipboardData.getData('text/plain'))})});requestAnimationFrame(overflow)}
function setView(v){view=v;for(const id of ['templates','components','editor'])$('#'+(id==='templates'?'library':id)+'-view').hidden=id!==v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='editor'){draw();inspect()}else if(v==='templates')catalog();else componentCatalog();scrollTo({top:0,behavior:'instant'});history.replaceState(null,'','#'+v)}
function catalog(){const cats=['All',...new Set(R.templates.map(t=>t.category))];$('#filters').innerHTML=cats.map(c=>`<button data-category="${c}" class="${c===category?'active':''}">${c}</button>`).join('');$('#template-catalog').innerHTML=R.templates.filter(t=>category==='All'||t.category===category).map(t=>{const s=create(t.id,libraryDensity==='template'?undefined:libraryDensity);return`<article class="catalog-card"><div class="card-preview" data-template="${t.id}" role="button" tabindex="0" aria-label="Edit ${t.name}">${render(s)}</div><div class="catalog-meta"><div><h2>${t.name}</h2><p>${t.category} / ${s.density} / ${R.formats[t.format].name.split(' · ')[0]}</p></div><button data-template="${t.id}">Edit template ↗</button></div></article>`}).join('');$('#template-catalog').querySelectorAll('.card-preview').forEach(fit);IOEngine.scan($('#template-catalog'))}
function componentCatalog(){const root=$('#component-catalog');root.innerHTML=R.components.map(c=>{const s=create('opening');Object.assign(s,{blocks:[block(c.id)],format:'wide',surface:'white',frame:'none',layout:'grid'});return`<article class="catalog-card component"><div class="card-preview">${render(s,false,true)}</div><div class="catalog-meta"><div><h2>${c.name}</h2><p>${c.description}</p></div><button data-add="${c.id}">Add +</button></div><button class="component-export" data-export-component="${c.id}">Export component ↓</button></article>`}).join('');root.querySelectorAll('.card-preview').forEach(fit);IOEngine.scan(root)}
const options=(values,current)=>values.map(([v,t])=>`<option value="${v}" ${v===current?'selected':''}>${esc(t)}</option>`).join('');
const select=(name,label,values)=>`<label class="control"><span>${label}</span><select data-setting="${name}">${options(values,(name==='palette'?activeMaterial():state)[name])}</select></label>`;
const range=(name,label,min,max,step)=>`<label class="control"><span>${label}<output>${Number(activeMaterial()[name]).toFixed(2)}</output></span><input data-range="${name}" type="range" min="${min}" max="${max}" step="${step}" value="${activeMaterial()[name]}"></label>`;
const field=(path,label,value,rows=2)=>`<label class="control"><span>${esc(label)}</span><textarea data-field="${path}" rows="${rows}">${esc(value)}</textarea></label>`;
function inspect(){const el=$('#inspector-body');let html='';if(inspector==='layout'){
 html+=select('format','Format',Object.entries(R.formats).map(([id,v])=>[id,v.name]));html+=select('frame','Frame',[['none','Artwork only'],['iphone','iPhone'],['social','Social post'],['browser','Browser window']]);html+=select('surface','Page surface',[['white','White / black ink'],['black','Black / white ink'],['ember','Solar Ember / black ink']]);html+='<div class="control"><span>Content density</span><div class="segmented">'+['sparse','standard','detailed'].map(d=>`<button data-density="${d}" class="${state.density===d?'active':''}">${d[0].toUpperCase()+d.slice(1)}</button>`).join('')+'</div></div>';html+=select('layout','Arrangement',[['split','Split composition'],['poster','Stacked poster'],['document','Document'],['editorial','Editorial spread'],['grid','Modular grid'],['diagram','Diagram + context']]);html+='<h3>Components</h3><div class="block-list">'+state.blocks.map((b,i)=>`<div class="block-row"><span class="block-name">${R.components.find(c=>c.id===b.type).name}</span><button data-move="${i},-1" aria-label="Move component up" ${i===0?'disabled':''}>↑</button><button data-move="${i},1" aria-label="Move component down" ${i===state.blocks.length-1?'disabled':''}>↓</button><button data-remove="${i}" aria-label="Remove component">×</button></div>`).join('')+'</div><button class="add-block" data-open-components>Add a component +</button><p class="hint">Density loads the template’s component set. Your headline and introduction stay in place.</p>';
 }else if(inspector==='content'){
 html=field('title','Headline',state.title,3)+field('intro','Introduction',state.intro,3)+field('kicker','Top label',state.kicker,2)+field('footer','Footer',state.footer,2);
 state.blocks.forEach((b,i)=>{html+=`<h3>${i+1}. ${R.components.find(c=>c.id===b.type).name}</h3>`;if(b.type==='material')return;html+=field(`blocks.${i}.title`,'Heading',b.title);if('text'in b)html+=field(`blocks.${i}.text`,'Text',b.text,4);if('center'in b)html+=field(`blocks.${i}.center`,'Center label',b.center,1);if(b.items)html+=`<label class="control"><span>${['bars','ring'].includes(b.type)?'Data · label | value':'Rows · separate columns with |'}</span><textarea data-rows="${i}" rows="${Math.min(6,b.items.length+1)}">${esc(b.items.map(r=>r.join(' | ')).join('\n'))}</textarea></label>`;if(b.headers)html+=`<label class="control"><span>Column headings</span><input data-headers="${i}" value="${esc(b.headers.join(' | '))}"></label>`;if('source'in b)html+=field(`blocks.${i}.source`,'Source',b.source,3)})
 }else{const m=activeMaterial();html='<label class="control"><span>Apply to</span><select id="material-target">'+options([['all','Shared material'],...state.blocks.flatMap((b,i)=>b.type==='material'?[[String(i),'Window '+(i+1)+(b.appearance?' · independent':'')]]:[])],materialTarget)+'</select></label><div class="control"><span>Material family</span><div class="material-options">'+materials.map(id=>`<button data-material="${id}" class="${m.material===id?'active':''}">${id==='screen'?'Two-plate screen':id==='lines'?'Line screen':id[0].toUpperCase()+id.slice(1)}</button>`).join('')+'</div></div>'+select('palette','Palette',[['prism','Ember + Sky'],['blue','Blue'],['orange','Ember']])+range('grain','Grain',0,.24,.005);const caps=IOEngine.capabilities[m.material]||[];for(const [k,label,min,max,step]of [['seed','Arrangement',0,1,.001],['scale','Density',1,28,.1],['rotation','Angle',-3.14,3.14,.01],['offset','Position',-1,1,.01],['size','Field width',.25,1.2,.01],['displace','Warp',0,6,.01]])if(caps.includes(k))html+=range(k,label,min,max,step);if(!state.blocks.some(b=>b.type==='material'))html+='<button class="add-block" data-add="material">Add material window +</button>';if(materialTarget!=='all')html+='<button class="add-block" data-use-shared>Use shared material</button>';html+='<p class="hint">Select a window to give it its own material. Text and diagrams stay independent.</p>'}
 el.innerHTML=html;
}
function download(name,contents,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([contents],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function exported(s,only=false){const B=IOBundle,safe=x=>x.replace(/<\/script/gi,'<\\/script'),payload=JSON.stringify(s).replace(/</g,'\\u003c');const script=`const payload=document.querySelector('#composition-project'),project=JSON.parse(payload.textContent);const preview=new URLSearchParams(location.search).has('preview');if(preview)document.body.classList.add('preview-export');function fit(){const c=document.querySelector('.composition-fit'),w=+c.dataset.width,h=+c.dataset.height,k=Math.max(.01,Math.min((innerWidth-(preview?0:40))/w,(innerHeight-(preview?0:110))/h));c.style.width=w*k+'px';c.style.height=h*k+'px';c.firstElementChild.style.transform='scale('+k+')';IOEngine.redraw()}fit();IOEngine.scan();if(preview)IOEngine.setPaused(true);document.fonts.ready.then(fit);addEventListener('resize',fit);document.querySelectorAll('[data-edit]').forEach(e=>e.addEventListener('input',()=>{const path=e.dataset.edit.split('.');let x=project;for(const k of path.slice(0,-1))x=x[k];x[path.at(-1)]=e.innerText;payload.textContent=JSON.stringify(project).replace(/</g,'\\\\u003c')}));document.querySelector('#save').onclick=()=>{const a=document.createElement('a');a.download='Impossible-composition-edited.html';a.href=URL.createObjectURL(new Blob(['<!doctype html>'+document.documentElement.outerHTML],{type:'text/html'}));a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)};document.querySelector('#pause').onclick=()=>IOEngine.setPaused(!IOEngine.paused);document.querySelector('#project').onclick=()=>{const a=document.createElement('a');a.download='Impossible-composition.json';a.href=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}));a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)};`;
 return`<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Impossible — ${esc(s.name)}</title><style>${B.fontCSS}\n${B.brandCSS}\n${IOStudioAssets.css}</style><script>${safe(B.tokenRuntime)}<\/script></head><body class="export-body">${render(s,true,only)}<div class="export-controls"><button id="save">Save edited HTML ↓</button><button id="project">Save project ↓</button><button id="pause">Pause / play</button></div><script type="application/json" id="composition-project">${payload}<\/script><script>${safe(B.fieldSource)}<\/script><script>${safe(B.materialSource)}<\/script><script>${safe(B.engine)}<\/script><script>${script}<\/script></body></html>`;
}
function add(id){if(state.blocks.length>=6){message('Use up to six components per composition.');return}state.blocks.push(block(id));persist();setView('editor');message('Component added. Arrange it in Layout.');}
function loadTemplate(id){materialTarget='all';state=create(id,libraryDensity==='template'?undefined:libraryDensity);persist();setView('editor')}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-template]');if(!b)return;const d=b.dataset;
 if(d.view)setView(d.view);if(d.template)loadTemplate(d.template);if(d.category){category=d.category;catalog()}if(d.inspector){inspector=d.inspector;document.querySelectorAll('[data-inspector]').forEach(x=>x.setAttribute('aria-selected',x===b));inspect()}if(d.openComponents!==undefined)setView('components');if(d.add)add(d.add);
 if(d.frameComponent){state.frame=d.frameComponent;if(d.frameComponent==='iphone')state.format='story';if(d.frameComponent==='social')state.format='square';persist();setView('editor')}
 if(d.remove!==undefined){materialTarget='all';state.blocks.splice(+d.remove,1);draw();inspect();persist()}
 if(d.move){materialTarget='all';const[i,n]=d.move.split(',').map(Number),j=i+n;if(j>=0&&j<state.blocks.length)[state.blocks[i],state.blocks[j]]=[state.blocks[j],state.blocks[i]];draw();inspect();persist()}
 if(d.density){materialTarget='all';state.density=d.density;const types=R.templates.find(t=>t.id===state.template).blocks[d.density];state.blocks=types.map(type=>clone(state.blocks.find(b=>b.type===type)||block(type)));draw();inspect();persist()}
 if(d.useShared!==undefined){delete state.blocks[Number(materialTarget)].appearance;materialTarget='all';draw();inspect();persist()}
 if(d.material){const m=activeMaterial();m.material=d.material;Object.assign(m,Object.fromEntries(Object.entries(IOEngine.defaults[d.material]||{}).filter(([k])=>['rotation','scale','offset','displace'].includes(k))));draw();inspect();persist()}
 if(d.exportComponent){const s=create('opening');Object.assign(s,{blocks:[block(d.exportComponent)],format:'wide',surface:'white',frame:'none',layout:'grid',name:R.components.find(c=>c.id===d.exportComponent).name});download('Impossible-component-'+d.exportComponent+'.html',exported(s,true),'text/html')}
});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.card-preview[data-template]')){e.preventDefault();loadTemplate(e.target.dataset.template)}});
$('#library-density').onchange=e=>{libraryDensity=e.target.value;catalog()};$('#inspector-body').addEventListener('change',e=>{const d=e.target.dataset;if(e.target.id==='material-target'){materialTarget=e.target.value;inspect()}if(d.setting){(d.setting==='palette'?activeMaterial():state)[d.setting]=e.target.value;if(d.setting==='frame'&&state.frame==='iphone')state.format='story';if(d.setting==='frame'&&state.frame==='social')state.format='square';draw();inspect();persist()}if(d.field){put(d.field,e.target.value);draw();persist()}if(d.rows!==undefined){const i=+d.rows,b=state.blocks[i],numeric=['bars','ring'].includes(b.type);const rows=e.target.value.trim().split('\n').filter(Boolean).slice(0,b.type==='process'||b.type==='timeline'||b.type==='network'?4:12).map(r=>r.split('|').map(x=>x.trim()));if(numeric&&rows.some(r=>r.length!==2||!Number.isFinite(Number(r[1]))||Number(r[1])<0)){message('Use one label and a nonnegative value per line, separated by |.');return}b.items=rows.map(r=>numeric?[r[0],Number(r[1])]:r);draw();persist()}if(d.headers!==undefined){state.blocks[+d.headers].headers=e.target.value.split('|').map(x=>x.trim());draw();persist()}});
$('#inspector-body').addEventListener('input',e=>{const k=e.target.dataset.range;if(!k)return;const m=activeMaterial();m[k]=+e.target.value;e.target.parentElement.querySelector('output').value=m[k].toFixed(2);$('#studio-stage').querySelectorAll('canvas').forEach(c=>{const v=state.blocks[+c.dataset.blockIndex]?.appearance||state;c.dataset[k]=v[k];IOEngine.draw(c,IOEngine.time)});persist()});
$('#zoom').onclick=()=>{zoom=!zoom;$('#zoom').textContent=zoom?'Fit':'100%';$('#zoom').setAttribute('aria-pressed',zoom);$('#studio-stage').classList.toggle('zoomed',zoom);fit($('#studio-stage'));IOEngine.redraw()};$('#guides').onclick=()=>{guides=!guides;$('#guides').setAttribute('aria-pressed',guides);draw()};function syncMotion(){const b=$('#motion'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;b.textContent=reduced?'Reduced motion':IOEngine.paused?'Play motion':'Pause motion';b.disabled=reduced;b.setAttribute('aria-pressed',IOEngine.paused)}$('#motion').onclick=()=>{IOEngine.setPaused(!IOEngine.paused);syncMotion()};matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',syncMotion);syncMotion();
$('#save-project').onclick=()=>download('Impossible-'+state.template+'.json',JSON.stringify(state,null,2),'application/json');$('#export-html').onclick=()=>{document.activeElement?.blur();download('Impossible-'+state.template+'.html',exported(state),'text/html')};
$('#import-project').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw Error('Project files must be under 2 MB.');state=validate(JSON.parse(await file.text()));persist();setView('editor');message('Project opened.')}catch(err){message(err.message)}e.target.value=''};
addEventListener('resize',()=>{if(view==='editor'){fit($('#studio-stage'));overflow()}else document.querySelectorAll('.card-preview').forEach(fit);IOEngine.redraw()});document.fonts.ready.then(()=>{document.querySelectorAll('.card-preview').forEach(fit);if(view==='editor')draw()});
window.IOStudio={registry:R,create,validate,render,exported,component,dimensions,get state(){return clone(state)},load(p){materialTarget='all';state=validate(p);persist();setView('editor')},select:loadTemplate,setView,overflow};const route=location.hash.slice(1);if(route.startsWith('template/')&&R.templates.some(t=>t.id===route.slice(9)))loadTemplate(route.slice(9));else setView(['templates','components','editor'].includes(route)?route:'templates');
})();
